// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bootstrap

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeferModule creates a new instance of MockDeferModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeferModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeferModule {
	mock := &MockDeferModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeferModule is an autogenerated mock type for the DeferModule type
type MockDeferModule struct {
	mock.Mock
}

type MockDeferModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeferModule) EXPECT() *MockDeferModule_Expecter {
	return &MockDeferModule_Expecter{mock: &_m.Mock}
}

// Defer provides a mock function for the type MockDeferModule
func (_mock *MockDeferModule) Defer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Defer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeferModule_Defer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Defer'
type MockDeferModule_Defer_Call struct {
	*mock.Call
}

// Defer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeferModule_Expecter) Defer(ctx any) *MockDeferModule_Defer_Call {
	return &MockDeferModule_Defer_Call{Call: _e.mock.On("Defer", ctx)}
}

func (_c *MockDeferModule_Defer_Call) Run(run func(ctx context.Context)) *MockDeferModule_Defer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeferModule_Defer_Call) Return(err error) *MockDeferModule_Defer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeferModule_Defer_Call) RunAndReturn(run func(ctx context.Context) error) *MockDeferModule_Defer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDestroyModule creates a new instance of MockDestroyModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDestroyModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDestroyModule {
	mock := &MockDestroyModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDestroyModule is an autogenerated mock type for the DestroyModule type
type MockDestroyModule struct {
	mock.Mock
}

type MockDestroyModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDestroyModule) EXPECT() *MockDestroyModule_Expecter {
	return &MockDestroyModule_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function for the type MockDestroyModule
func (_mock *MockDestroyModule) Destroy() {
	_mock.Called()
	return
}

// MockDestroyModule_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockDestroyModule_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockDestroyModule_Expecter) Destroy() *MockDestroyModule_Destroy_Call {
	return &MockDestroyModule_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockDestroyModule_Destroy_Call) Run(run func()) *MockDestroyModule_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDestroyModule_Destroy_Call) Return() *MockDestroyModule_Destroy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDestroyModule_Destroy_Call) RunAndReturn(run func()) *MockDestroyModule_Destroy_Call {
	_c.Run(run)
	return _c
}

// NewMockReadyModule creates a new instance of MockReadyModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadyModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadyModule {
	mock := &MockReadyModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadyModule is an autogenerated mock type for the ReadyModule type
type MockReadyModule struct {
	mock.Mock
}

type MockReadyModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadyModule) EXPECT() *MockReadyModule_Expecter {
	return &MockReadyModule_Expecter{mock: &_m.Mock}
}

// Ready provides a mock function for the type MockReadyModule
func (_mock *MockReadyModule) Ready(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadyModule_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockReadyModule_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockReadyModule_Expecter) Ready(context1 any) *MockReadyModule_Ready_Call {
	return &MockReadyModule_Ready_Call{Call: _e.mock.On("Ready", context1)}
}

func (_c *MockReadyModule_Ready_Call) Run(run func(context1 context.Context)) *MockReadyModule_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadyModule_Ready_Call) Return(err error) *MockReadyModule_Ready_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadyModule_Ready_Call) RunAndReturn(run func(context1 context.Context) error) *MockReadyModule_Ready_Call {
	_c.Call.Return(run)
	return _c
}
