template: testify
template-data:
  unroll-variadic: true
packages:
  pan/internal:
    config:
      all: true
      dir: mocks/{{ replaceAll .SrcPackagePath "internal" "internal_" }}/{{ .SrcPackageName }}
      filename: "mocks.go"
      recursive: true
  pan/pkg:
    config:
      all: true
      dir: mocks/{{ .SrcPackagePath }}
      filename: "mocks.go"
      recursive: true
