with-expecter: true
packages:
  pan/memory:
    interfaces:
      HashCode:
  pan/core:
    interfaces:
      Context:
      Handler:
      App:
  pan/broadcast:
    interfaces:
      Net:
      ServiceSettings:
      Context:
  pan/peer:
    interfaces:
      Context:
      NodeServe:
      Node:
      NodeStream:
      NodeDialer:
      NodeHandshake:
      Peer:
      PeerIdGenerator:
