with-expecter: true
packages:
  pan/core:
    interfaces:
      Context:
      Handler:
      App:
  pan/broadcast:
    interfaces:
      Net:
      BroadcastAddrGenerator:
      Model:
      ServiceSettings:
      Context:
  pan/peer:
    interfaces:
      Context:
      NodeServe:
      Node:
      NodeStream:
      NodeDialer:
      Peer:
      PeerRoute:
      PeerRepository:
      PeerRouteRepository:        
