// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.9
// source: extfs/proto/remote_file.proto

package remotefile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteFileRecordList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*RemoteFileRecord `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *RemoteFileRecordList) Reset() {
	*x = RemoteFileRecordList{}
	mi := &file_extfs_proto_remote_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteFileRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFileRecordList) ProtoMessage() {}

func (x *RemoteFileRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFileRecordList.ProtoReflect.Descriptor instead.
func (*RemoteFileRecordList) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_file_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteFileRecordList) GetItems() []*RemoteFileRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

type RemoteFileRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt  int64  `protobuf:"varint,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ItemID     uint32 `protobuf:"varint,4,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	Name       string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	FileType   string `protobuf:"bytes,6,opt,name=FileType,proto3" json:"FileType,omitempty"`
	FilePath   string `protobuf:"bytes,7,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	ParentPath string `protobuf:"bytes,8,opt,name=ParentPath,proto3" json:"ParentPath,omitempty"`
	MimeType   string `protobuf:"bytes,9,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	Size       int64  `protobuf:"varint,10,opt,name=Size,proto3" json:"Size,omitempty"`
	Available  bool   `protobuf:"varint,11,opt,name=Available,proto3" json:"Available,omitempty"`
}

func (x *RemoteFileRecord) Reset() {
	*x = RemoteFileRecord{}
	mi := &file_extfs_proto_remote_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteFileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFileRecord) ProtoMessage() {}

func (x *RemoteFileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFileRecord.ProtoReflect.Descriptor instead.
func (*RemoteFileRecord) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_file_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteFileRecord) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RemoteFileRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RemoteFileRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RemoteFileRecord) GetItemID() uint32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *RemoteFileRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteFileRecord) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *RemoteFileRecord) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RemoteFileRecord) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *RemoteFileRecord) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RemoteFileRecord) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RemoteFileRecord) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type RemoteFileRecordSearchCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID     uint32  `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	ParentPath *string `protobuf:"bytes,2,opt,name=ParentPath,proto3,oneof" json:"ParentPath,omitempty"`
}

func (x *RemoteFileRecordSearchCondition) Reset() {
	*x = RemoteFileRecordSearchCondition{}
	mi := &file_extfs_proto_remote_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteFileRecordSearchCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFileRecordSearchCondition) ProtoMessage() {}

func (x *RemoteFileRecordSearchCondition) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFileRecordSearchCondition.ProtoReflect.Descriptor instead.
func (*RemoteFileRecordSearchCondition) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_file_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteFileRecordSearchCondition) GetItemID() uint32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *RemoteFileRecordSearchCondition) GetParentPath() string {
	if x != nil && x.ParentPath != nil {
		return *x.ParentPath
	}
	return ""
}

type RemoteFileRecordSelectCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID     uint32 `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	ParentPath string `protobuf:"bytes,2,opt,name=ParentPath,proto3" json:"ParentPath,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *RemoteFileRecordSelectCondition) Reset() {
	*x = RemoteFileRecordSelectCondition{}
	mi := &file_extfs_proto_remote_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteFileRecordSelectCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFileRecordSelectCondition) ProtoMessage() {}

func (x *RemoteFileRecordSelectCondition) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFileRecordSelectCondition.ProtoReflect.Descriptor instead.
func (*RemoteFileRecordSelectCondition) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_file_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteFileRecordSelectCondition) GetItemID() uint32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *RemoteFileRecordSelectCondition) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *RemoteFileRecordSelectCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_extfs_proto_remote_file_proto protoreflect.FileDescriptor

var file_extfs_proto_remote_file_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x78, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x4a, 0x0a, 0x14, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x66, 0x69, 0x6c, 0x65, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xb0, 0x02, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x4d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x6d, 0x0a, 0x1f, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x6d, 0x0a, 0x1f, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x65, 0x78, 0x74, 0x66,
	0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x3b, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extfs_proto_remote_file_proto_rawDescOnce sync.Once
	file_extfs_proto_remote_file_proto_rawDescData = file_extfs_proto_remote_file_proto_rawDesc
)

func file_extfs_proto_remote_file_proto_rawDescGZIP() []byte {
	file_extfs_proto_remote_file_proto_rawDescOnce.Do(func() {
		file_extfs_proto_remote_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_extfs_proto_remote_file_proto_rawDescData)
	})
	return file_extfs_proto_remote_file_proto_rawDescData
}

var file_extfs_proto_remote_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_extfs_proto_remote_file_proto_goTypes = []any{
	(*RemoteFileRecordList)(nil),            // 0: remotefile.RemoteFileRecordList
	(*RemoteFileRecord)(nil),                // 1: remotefile.RemoteFileRecord
	(*RemoteFileRecordSearchCondition)(nil), // 2: remotefile.RemoteFileRecordSearchCondition
	(*RemoteFileRecordSelectCondition)(nil), // 3: remotefile.RemoteFileRecordSelectCondition
}
var file_extfs_proto_remote_file_proto_depIdxs = []int32{
	1, // 0: remotefile.RemoteFileRecordList.Items:type_name -> remotefile.RemoteFileRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extfs_proto_remote_file_proto_init() }
func file_extfs_proto_remote_file_proto_init() {
	if File_extfs_proto_remote_file_proto != nil {
		return
	}
	file_extfs_proto_remote_file_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extfs_proto_remote_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extfs_proto_remote_file_proto_goTypes,
		DependencyIndexes: file_extfs_proto_remote_file_proto_depIdxs,
		MessageInfos:      file_extfs_proto_remote_file_proto_msgTypes,
	}.Build()
	File_extfs_proto_remote_file_proto = out.File
	file_extfs_proto_remote_file_proto_rawDesc = nil
	file_extfs_proto_remote_file_proto_goTypes = nil
	file_extfs_proto_remote_file_proto_depIdxs = nil
}
