// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"pan/pkg/config"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// SetupToRepository provides a mock function for the type MockRepository
func (_mock *MockRepository) SetupToRepository(db RepositoryDB) error {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for SetupToRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryDB) error); ok {
		r0 = returnFunc(db)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetupToRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToRepository'
type MockRepository_SetupToRepository_Call struct {
	*mock.Call
}

// SetupToRepository is a helper method to define mock.On call
//   - db RepositoryDB
func (_e *MockRepository_Expecter) SetupToRepository(db any) *MockRepository_SetupToRepository_Call {
	return &MockRepository_SetupToRepository_Call{Call: _e.mock.On("SetupToRepository", db)}
}

func (_c *MockRepository_SetupToRepository_Call) Run(run func(db RepositoryDB)) *MockRepository_SetupToRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryDB
		if args[0] != nil {
			arg0 = args[0].(RepositoryDB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_SetupToRepository_Call) Return(err error) *MockRepository_SetupToRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetupToRepository_Call) RunAndReturn(run func(db RepositoryDB) error) *MockRepository_SetupToRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryConfig creates a new instance of MockRepositoryConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryConfig {
	mock := &MockRepositoryConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryConfig is an autogenerated mock type for the RepositoryConfig type
type MockRepositoryConfig struct {
	mock.Mock
}

type MockRepositoryConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryConfig) EXPECT() *MockRepositoryConfig_Expecter {
	return &MockRepositoryConfig_Expecter{mock: &_m.Mock}
}

// BasePath provides a mock function for the type MockRepositoryConfig
func (_mock *MockRepositoryConfig) BasePath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BasePath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepositoryConfig_BasePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BasePath'
type MockRepositoryConfig_BasePath_Call struct {
	*mock.Call
}

// BasePath is a helper method to define mock.On call
func (_e *MockRepositoryConfig_Expecter) BasePath() *MockRepositoryConfig_BasePath_Call {
	return &MockRepositoryConfig_BasePath_Call{Call: _e.mock.On("BasePath")}
}

func (_c *MockRepositoryConfig_BasePath_Call) Run(run func()) *MockRepositoryConfig_BasePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryConfig_BasePath_Call) Return(s string) *MockRepositoryConfig_BasePath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRepositoryConfig_BasePath_Call) RunAndReturn(run func() string) *MockRepositoryConfig_BasePath_Call {
	_c.Call.Return(run)
	return _c
}

// TempPath provides a mock function for the type MockRepositoryConfig
func (_mock *MockRepositoryConfig) TempPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TempPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepositoryConfig_TempPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TempPath'
type MockRepositoryConfig_TempPath_Call struct {
	*mock.Call
}

// TempPath is a helper method to define mock.On call
func (_e *MockRepositoryConfig_Expecter) TempPath() *MockRepositoryConfig_TempPath_Call {
	return &MockRepositoryConfig_TempPath_Call{Call: _e.mock.On("TempPath")}
}

func (_c *MockRepositoryConfig_TempPath_Call) Run(run func()) *MockRepositoryConfig_TempPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryConfig_TempPath_Call) Return(s string) *MockRepositoryConfig_TempPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRepositoryConfig_TempPath_Call) RunAndReturn(run func() string) *MockRepositoryConfig_TempPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryConfigListener creates a new instance of MockRepositoryConfigListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryConfigListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryConfigListener {
	mock := &MockRepositoryConfigListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryConfigListener is an autogenerated mock type for the RepositoryConfigListener type
type MockRepositoryConfigListener struct {
	mock.Mock
}

type MockRepositoryConfigListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryConfigListener) EXPECT() *MockRepositoryConfigListener_Expecter {
	return &MockRepositoryConfigListener_Expecter{mock: &_m.Mock}
}

// OnConfigUpdated provides a mock function for the type MockRepositoryConfigListener
func (_mock *MockRepositoryConfigListener) OnConfigUpdated(config RepositoryConfig) {
	_mock.Called(config)
	return
}

// MockRepositoryConfigListener_OnConfigUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigUpdated'
type MockRepositoryConfigListener_OnConfigUpdated_Call struct {
	*mock.Call
}

// OnConfigUpdated is a helper method to define mock.On call
//   - config RepositoryConfig
func (_e *MockRepositoryConfigListener_Expecter) OnConfigUpdated(config any) *MockRepositoryConfigListener_OnConfigUpdated_Call {
	return &MockRepositoryConfigListener_OnConfigUpdated_Call{Call: _e.mock.On("OnConfigUpdated", config)}
}

func (_c *MockRepositoryConfigListener_OnConfigUpdated_Call) Run(run func(config RepositoryConfig)) *MockRepositoryConfigListener_OnConfigUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryConfig
		if args[0] != nil {
			arg0 = args[0].(RepositoryConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryConfigListener_OnConfigUpdated_Call) Return() *MockRepositoryConfigListener_OnConfigUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepositoryConfigListener_OnConfigUpdated_Call) RunAndReturn(run func(config RepositoryConfig)) *MockRepositoryConfigListener_OnConfigUpdated_Call {
	_c.Run(run)
	return _c
}

// NewMockRepositoryConfigurer creates a new instance of MockRepositoryConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryConfigurer {
	mock := &MockRepositoryConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryConfigurer is an autogenerated mock type for the RepositoryConfigurer type
type MockRepositoryConfigurer struct {
	mock.Mock
}

type MockRepositoryConfigurer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryConfigurer) EXPECT() *MockRepositoryConfigurer_Expecter {
	return &MockRepositoryConfigurer_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockRepositoryConfigurer
func (_mock *MockRepositoryConfigurer) Config() RepositoryConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 RepositoryConfig
	if returnFunc, ok := ret.Get(0).(func() RepositoryConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(RepositoryConfig)
		}
	}
	return r0
}

// MockRepositoryConfigurer_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockRepositoryConfigurer_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockRepositoryConfigurer_Expecter) Config() *MockRepositoryConfigurer_Config_Call {
	return &MockRepositoryConfigurer_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockRepositoryConfigurer_Config_Call) Run(run func()) *MockRepositoryConfigurer_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryConfigurer_Config_Call) Return(repositoryConfig RepositoryConfig) *MockRepositoryConfigurer_Config_Call {
	_c.Call.Return(repositoryConfig)
	return _c
}

func (_c *MockRepositoryConfigurer_Config_Call) RunAndReturn(run func() RepositoryConfig) *MockRepositoryConfigurer_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigListeners provides a mock function for the type MockRepositoryConfigurer
func (_mock *MockRepositoryConfigurer) ConfigListeners() []config.ConfigurerListener[RepositoryConfig] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigListeners")
	}

	var r0 []config.ConfigurerListener[RepositoryConfig]
	if returnFunc, ok := ret.Get(0).(func() []config.ConfigurerListener[RepositoryConfig]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ConfigurerListener[RepositoryConfig])
		}
	}
	return r0
}

// MockRepositoryConfigurer_ConfigListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigListeners'
type MockRepositoryConfigurer_ConfigListeners_Call struct {
	*mock.Call
}

// ConfigListeners is a helper method to define mock.On call
func (_e *MockRepositoryConfigurer_Expecter) ConfigListeners() *MockRepositoryConfigurer_ConfigListeners_Call {
	return &MockRepositoryConfigurer_ConfigListeners_Call{Call: _e.mock.On("ConfigListeners")}
}

func (_c *MockRepositoryConfigurer_ConfigListeners_Call) Run(run func()) *MockRepositoryConfigurer_ConfigListeners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryConfigurer_ConfigListeners_Call) Return(configurerListeners []config.ConfigurerListener[RepositoryConfig]) *MockRepositoryConfigurer_ConfigListeners_Call {
	_c.Call.Return(configurerListeners)
	return _c
}

func (_c *MockRepositoryConfigurer_ConfigListeners_Call) RunAndReturn(run func() []config.ConfigurerListener[RepositoryConfig]) *MockRepositoryConfigurer_ConfigListeners_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type MockRepositoryConfigurer
func (_mock *MockRepositoryConfigurer) Configure(config1 RepositoryConfig) error {
	ret := _mock.Called(config1)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryConfig) error); ok {
		r0 = returnFunc(config1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryConfigurer_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockRepositoryConfigurer_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - config1 RepositoryConfig
func (_e *MockRepositoryConfigurer_Expecter) Configure(config1 any) *MockRepositoryConfigurer_Configure_Call {
	return &MockRepositoryConfigurer_Configure_Call{Call: _e.mock.On("Configure", config1)}
}

func (_c *MockRepositoryConfigurer_Configure_Call) Run(run func(config1 RepositoryConfig)) *MockRepositoryConfigurer_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryConfig
		if args[0] != nil {
			arg0 = args[0].(RepositoryConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryConfigurer_Configure_Call) Return(err error) *MockRepositoryConfigurer_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryConfigurer_Configure_Call) RunAndReturn(run func(config1 RepositoryConfig) error) *MockRepositoryConfigurer_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockRepositoryConfigurer
func (_mock *MockRepositoryConfigurer) Subscribe(listener config.ConfigurerListener[RepositoryConfig]) {
	_mock.Called(listener)
	return
}

// MockRepositoryConfigurer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockRepositoryConfigurer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[RepositoryConfig]
func (_e *MockRepositoryConfigurer_Expecter) Subscribe(listener any) *MockRepositoryConfigurer_Subscribe_Call {
	return &MockRepositoryConfigurer_Subscribe_Call{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *MockRepositoryConfigurer_Subscribe_Call) Run(run func(listener config.ConfigurerListener[RepositoryConfig])) *MockRepositoryConfigurer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[RepositoryConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[RepositoryConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryConfigurer_Subscribe_Call) Return() *MockRepositoryConfigurer_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepositoryConfigurer_Subscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[RepositoryConfig])) *MockRepositoryConfigurer_Subscribe_Call {
	_c.Run(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockRepositoryConfigurer
func (_mock *MockRepositoryConfigurer) Unsubscribe(listener config.ConfigurerListener[RepositoryConfig]) {
	_mock.Called(listener)
	return
}

// MockRepositoryConfigurer_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockRepositoryConfigurer_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[RepositoryConfig]
func (_e *MockRepositoryConfigurer_Expecter) Unsubscribe(listener any) *MockRepositoryConfigurer_Unsubscribe_Call {
	return &MockRepositoryConfigurer_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", listener)}
}

func (_c *MockRepositoryConfigurer_Unsubscribe_Call) Run(run func(listener config.ConfigurerListener[RepositoryConfig])) *MockRepositoryConfigurer_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[RepositoryConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[RepositoryConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryConfigurer_Unsubscribe_Call) Return() *MockRepositoryConfigurer_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepositoryConfigurer_Unsubscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[RepositoryConfig])) *MockRepositoryConfigurer_Unsubscribe_Call {
	_c.Run(run)
	return _c
}

// NewMockRepositoryDBModule creates a new instance of MockRepositoryDBModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryDBModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryDBModule {
	mock := &MockRepositoryDBModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryDBModule is an autogenerated mock type for the RepositoryDBModule type
type MockRepositoryDBModule struct {
	mock.Mock
}

type MockRepositoryDBModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryDBModule) EXPECT() *MockRepositoryDBModule_Expecter {
	return &MockRepositoryDBModule_Expecter{mock: &_m.Mock}
}

// DBName provides a mock function for the type MockRepositoryDBModule
func (_mock *MockRepositoryDBModule) DBName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepositoryDBModule_DBName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBName'
type MockRepositoryDBModule_DBName_Call struct {
	*mock.Call
}

// DBName is a helper method to define mock.On call
func (_e *MockRepositoryDBModule_Expecter) DBName() *MockRepositoryDBModule_DBName_Call {
	return &MockRepositoryDBModule_DBName_Call{Call: _e.mock.On("DBName")}
}

func (_c *MockRepositoryDBModule_DBName_Call) Run(run func()) *MockRepositoryDBModule_DBName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryDBModule_DBName_Call) Return(s string) *MockRepositoryDBModule_DBName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRepositoryDBModule_DBName_Call) RunAndReturn(run func() string) *MockRepositoryDBModule_DBName_Call {
	_c.Call.Return(run)
	return _c
}

// SetupToRepository provides a mock function for the type MockRepositoryDBModule
func (_mock *MockRepositoryDBModule) SetupToRepository(db RepositoryDB) error {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for SetupToRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryDB) error); ok {
		r0 = returnFunc(db)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryDBModule_SetupToRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToRepository'
type MockRepositoryDBModule_SetupToRepository_Call struct {
	*mock.Call
}

// SetupToRepository is a helper method to define mock.On call
//   - db RepositoryDB
func (_e *MockRepositoryDBModule_Expecter) SetupToRepository(db any) *MockRepositoryDBModule_SetupToRepository_Call {
	return &MockRepositoryDBModule_SetupToRepository_Call{Call: _e.mock.On("SetupToRepository", db)}
}

func (_c *MockRepositoryDBModule_SetupToRepository_Call) Run(run func(db RepositoryDB)) *MockRepositoryDBModule_SetupToRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryDB
		if args[0] != nil {
			arg0 = args[0].(RepositoryDB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryDBModule_SetupToRepository_Call) Return(err error) *MockRepositoryDBModule_SetupToRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryDBModule_SetupToRepository_Call) RunAndReturn(run func(db RepositoryDB) error) *MockRepositoryDBModule_SetupToRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryManager creates a new instance of MockRepositoryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryManager {
	mock := &MockRepositoryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryManager is an autogenerated mock type for the RepositoryManager type
type MockRepositoryManager struct {
	mock.Mock
}

type MockRepositoryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryManager) EXPECT() *MockRepositoryManager_Expecter {
	return &MockRepositoryManager_Expecter{mock: &_m.Mock}
}

// AttachBaseModule provides a mock function for the type MockRepositoryManager
func (_mock *MockRepositoryManager) AttachBaseModule(module RepositoryDBModule) error {
	ret := _mock.Called(module)

	if len(ret) == 0 {
		panic("no return value specified for AttachBaseModule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryDBModule) error); ok {
		r0 = returnFunc(module)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryManager_AttachBaseModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachBaseModule'
type MockRepositoryManager_AttachBaseModule_Call struct {
	*mock.Call
}

// AttachBaseModule is a helper method to define mock.On call
//   - module RepositoryDBModule
func (_e *MockRepositoryManager_Expecter) AttachBaseModule(module any) *MockRepositoryManager_AttachBaseModule_Call {
	return &MockRepositoryManager_AttachBaseModule_Call{Call: _e.mock.On("AttachBaseModule", module)}
}

func (_c *MockRepositoryManager_AttachBaseModule_Call) Run(run func(module RepositoryDBModule)) *MockRepositoryManager_AttachBaseModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryDBModule
		if args[0] != nil {
			arg0 = args[0].(RepositoryDBModule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryManager_AttachBaseModule_Call) Return(err error) *MockRepositoryManager_AttachBaseModule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryManager_AttachBaseModule_Call) RunAndReturn(run func(module RepositoryDBModule) error) *MockRepositoryManager_AttachBaseModule_Call {
	_c.Call.Return(run)
	return _c
}

// AttachTempModule provides a mock function for the type MockRepositoryManager
func (_mock *MockRepositoryManager) AttachTempModule(module RepositoryDBModule) error {
	ret := _mock.Called(module)

	if len(ret) == 0 {
		panic("no return value specified for AttachTempModule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryDBModule) error); ok {
		r0 = returnFunc(module)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryManager_AttachTempModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachTempModule'
type MockRepositoryManager_AttachTempModule_Call struct {
	*mock.Call
}

// AttachTempModule is a helper method to define mock.On call
//   - module RepositoryDBModule
func (_e *MockRepositoryManager_Expecter) AttachTempModule(module any) *MockRepositoryManager_AttachTempModule_Call {
	return &MockRepositoryManager_AttachTempModule_Call{Call: _e.mock.On("AttachTempModule", module)}
}

func (_c *MockRepositoryManager_AttachTempModule_Call) Run(run func(module RepositoryDBModule)) *MockRepositoryManager_AttachTempModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryDBModule
		if args[0] != nil {
			arg0 = args[0].(RepositoryDBModule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryManager_AttachTempModule_Call) Return(err error) *MockRepositoryManager_AttachTempModule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryManager_AttachTempModule_Call) RunAndReturn(run func(module RepositoryDBModule) error) *MockRepositoryManager_AttachTempModule_Call {
	_c.Call.Return(run)
	return _c
}

// DetachBaseModule provides a mock function for the type MockRepositoryManager
func (_mock *MockRepositoryManager) DetachBaseModule(module RepositoryDBModule) error {
	ret := _mock.Called(module)

	if len(ret) == 0 {
		panic("no return value specified for DetachBaseModule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryDBModule) error); ok {
		r0 = returnFunc(module)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryManager_DetachBaseModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachBaseModule'
type MockRepositoryManager_DetachBaseModule_Call struct {
	*mock.Call
}

// DetachBaseModule is a helper method to define mock.On call
//   - module RepositoryDBModule
func (_e *MockRepositoryManager_Expecter) DetachBaseModule(module any) *MockRepositoryManager_DetachBaseModule_Call {
	return &MockRepositoryManager_DetachBaseModule_Call{Call: _e.mock.On("DetachBaseModule", module)}
}

func (_c *MockRepositoryManager_DetachBaseModule_Call) Run(run func(module RepositoryDBModule)) *MockRepositoryManager_DetachBaseModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryDBModule
		if args[0] != nil {
			arg0 = args[0].(RepositoryDBModule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryManager_DetachBaseModule_Call) Return(err error) *MockRepositoryManager_DetachBaseModule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryManager_DetachBaseModule_Call) RunAndReturn(run func(module RepositoryDBModule) error) *MockRepositoryManager_DetachBaseModule_Call {
	_c.Call.Return(run)
	return _c
}

// DetachTempModule provides a mock function for the type MockRepositoryManager
func (_mock *MockRepositoryManager) DetachTempModule(module RepositoryDBModule) error {
	ret := _mock.Called(module)

	if len(ret) == 0 {
		panic("no return value specified for DetachTempModule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(RepositoryDBModule) error); ok {
		r0 = returnFunc(module)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryManager_DetachTempModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachTempModule'
type MockRepositoryManager_DetachTempModule_Call struct {
	*mock.Call
}

// DetachTempModule is a helper method to define mock.On call
//   - module RepositoryDBModule
func (_e *MockRepositoryManager_Expecter) DetachTempModule(module any) *MockRepositoryManager_DetachTempModule_Call {
	return &MockRepositoryManager_DetachTempModule_Call{Call: _e.mock.On("DetachTempModule", module)}
}

func (_c *MockRepositoryManager_DetachTempModule_Call) Run(run func(module RepositoryDBModule)) *MockRepositoryManager_DetachTempModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RepositoryDBModule
		if args[0] != nil {
			arg0 = args[0].(RepositoryDBModule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryManager_DetachTempModule_Call) Return(err error) *MockRepositoryManager_DetachTempModule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryManager_DetachTempModule_Call) RunAndReturn(run func(module RepositoryDBModule) error) *MockRepositoryManager_DetachTempModule_Call {
	_c.Call.Return(run)
	return _c
}
