// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.9
// source: extfs/proto/remote_filestream.proto

package remoteitem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteFileStreamSelectCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID   uint32 `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	FilePath string `protobuf:"bytes,2,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Offset   int64  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *RemoteFileStreamSelectCondition) Reset() {
	*x = RemoteFileStreamSelectCondition{}
	mi := &file_extfs_proto_remote_filestream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteFileStreamSelectCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteFileStreamSelectCondition) ProtoMessage() {}

func (x *RemoteFileStreamSelectCondition) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_filestream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteFileStreamSelectCondition.ProtoReflect.Descriptor instead.
func (*RemoteFileStreamSelectCondition) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_filestream_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteFileStreamSelectCondition) GetItemID() uint32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *RemoteFileStreamSelectCondition) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RemoteFileStreamSelectCondition) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_extfs_proto_remote_filestream_proto protoreflect.FileDescriptor

var file_extfs_proto_remote_filestream_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x78, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x6d, 0x0a, 0x1f, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x42, 0x1e, 0x5a, 0x1c, 0x65, 0x78, 0x74, 0x66, 0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x3b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x69, 0x74, 0x65, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extfs_proto_remote_filestream_proto_rawDescOnce sync.Once
	file_extfs_proto_remote_filestream_proto_rawDescData = file_extfs_proto_remote_filestream_proto_rawDesc
)

func file_extfs_proto_remote_filestream_proto_rawDescGZIP() []byte {
	file_extfs_proto_remote_filestream_proto_rawDescOnce.Do(func() {
		file_extfs_proto_remote_filestream_proto_rawDescData = protoimpl.X.CompressGZIP(file_extfs_proto_remote_filestream_proto_rawDescData)
	})
	return file_extfs_proto_remote_filestream_proto_rawDescData
}

var file_extfs_proto_remote_filestream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extfs_proto_remote_filestream_proto_goTypes = []any{
	(*RemoteFileStreamSelectCondition)(nil), // 0: remoteitem.RemoteFileStreamSelectCondition
}
var file_extfs_proto_remote_filestream_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extfs_proto_remote_filestream_proto_init() }
func file_extfs_proto_remote_filestream_proto_init() {
	if File_extfs_proto_remote_filestream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extfs_proto_remote_filestream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extfs_proto_remote_filestream_proto_goTypes,
		DependencyIndexes: file_extfs_proto_remote_filestream_proto_depIdxs,
		MessageInfos:      file_extfs_proto_remote_filestream_proto_msgTypes,
	}.Build()
	File_extfs_proto_remote_filestream_proto = out.File
	file_extfs_proto_remote_filestream_proto_rawDesc = nil
	file_extfs_proto_remote_filestream_proto_goTypes = nil
	file_extfs_proto_remote_filestream_proto_depIdxs = nil
}
