// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runtime

import (
	"context"
	"reflect"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEngineExtensionModule creates a new instance of MockEngineExtensionModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngineExtensionModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngineExtensionModule {
	mock := &MockEngineExtensionModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEngineExtensionModule is an autogenerated mock type for the EngineExtensionModule type
type MockEngineExtensionModule struct {
	mock.Mock
}

type MockEngineExtensionModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngineExtensionModule) EXPECT() *MockEngineExtensionModule_Expecter {
	return &MockEngineExtensionModule_Expecter{mock: &_m.Mock}
}

// EngineTypes provides a mock function for the type MockEngineExtensionModule
func (_mock *MockEngineExtensionModule) EngineTypes() []reflect.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EngineTypes")
	}

	var r0 []reflect.Type
	if returnFunc, ok := ret.Get(0).(func() []reflect.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reflect.Type)
		}
	}
	return r0
}

// MockEngineExtensionModule_EngineTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EngineTypes'
type MockEngineExtensionModule_EngineTypes_Call struct {
	*mock.Call
}

// EngineTypes is a helper method to define mock.On call
func (_e *MockEngineExtensionModule_Expecter) EngineTypes() *MockEngineExtensionModule_EngineTypes_Call {
	return &MockEngineExtensionModule_EngineTypes_Call{Call: _e.mock.On("EngineTypes")}
}

func (_c *MockEngineExtensionModule_EngineTypes_Call) Run(run func()) *MockEngineExtensionModule_EngineTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngineExtensionModule_EngineTypes_Call) Return(types []reflect.Type) *MockEngineExtensionModule_EngineTypes_Call {
	_c.Call.Return(types)
	return _c
}

func (_c *MockEngineExtensionModule_EngineTypes_Call) RunAndReturn(run func() []reflect.Type) *MockEngineExtensionModule_EngineTypes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModule creates a new instance of MockModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModule {
	mock := &MockModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModule is an autogenerated mock type for the Module type
type MockModule struct {
	mock.Mock
}

type MockModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModule) EXPECT() *MockModule_Expecter {
	return &MockModule_Expecter{mock: &_m.Mock}
}

// TypeOfModule provides a mock function for the type MockModule
func (_mock *MockModule) TypeOfModule() []reflect.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeOfModule")
	}

	var r0 []reflect.Type
	if returnFunc, ok := ret.Get(0).(func() []reflect.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reflect.Type)
		}
	}
	return r0
}

// MockModule_TypeOfModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeOfModule'
type MockModule_TypeOfModule_Call struct {
	*mock.Call
}

// TypeOfModule is a helper method to define mock.On call
func (_e *MockModule_Expecter) TypeOfModule() *MockModule_TypeOfModule_Call {
	return &MockModule_TypeOfModule_Call{Call: _e.mock.On("TypeOfModule")}
}

func (_c *MockModule_TypeOfModule_Call) Run(run func()) *MockModule_TypeOfModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModule_TypeOfModule_Call) Return(types []reflect.Type) *MockModule_TypeOfModule_Call {
	_c.Call.Return(types)
	return _c
}

func (_c *MockModule_TypeOfModule_Call) RunAndReturn(run func() []reflect.Type) *MockModule_TypeOfModule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderModule creates a new instance of MockProviderModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderModule {
	mock := &MockProviderModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderModule is an autogenerated mock type for the ProviderModule type
type MockProviderModule struct {
	mock.Mock
}

type MockProviderModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderModule) EXPECT() *MockProviderModule_Expecter {
	return &MockProviderModule_Expecter{mock: &_m.Mock}
}

// Modules provides a mock function for the type MockProviderModule
func (_mock *MockProviderModule) Modules() []interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modules")
	}

	var r0 []interface{}
	if returnFunc, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	return r0
}

// MockProviderModule_Modules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modules'
type MockProviderModule_Modules_Call struct {
	*mock.Call
}

// Modules is a helper method to define mock.On call
func (_e *MockProviderModule_Expecter) Modules() *MockProviderModule_Modules_Call {
	return &MockProviderModule_Modules_Call{Call: _e.mock.On("Modules")}
}

func (_c *MockProviderModule_Modules_Call) Run(run func()) *MockProviderModule_Modules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProviderModule_Modules_Call) Return(ifaceVals []interface{}) *MockProviderModule_Modules_Call {
	_c.Call.Return(ifaceVals)
	return _c
}

func (_c *MockProviderModule_Modules_Call) RunAndReturn(run func() []interface{}) *MockProviderModule_Modules_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInitializeModule creates a new instance of MockInitializeModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInitializeModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInitializeModule {
	mock := &MockInitializeModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInitializeModule is an autogenerated mock type for the InitializeModule type
type MockInitializeModule struct {
	mock.Mock
}

type MockInitializeModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInitializeModule) EXPECT() *MockInitializeModule_Expecter {
	return &MockInitializeModule_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type MockInitializeModule
func (_mock *MockInitializeModule) Init(ctx context.Context, registry Registry) error {
	ret := _mock.Called(ctx, registry)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Registry) error); ok {
		r0 = returnFunc(ctx, registry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInitializeModule_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockInitializeModule_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - registry Registry
func (_e *MockInitializeModule_Expecter) Init(ctx any, registry any) *MockInitializeModule_Init_Call {
	return &MockInitializeModule_Init_Call{Call: _e.mock.On("Init", ctx, registry)}
}

func (_c *MockInitializeModule_Init_Call) Run(run func(ctx context.Context, registry Registry)) *MockInitializeModule_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Registry
		if args[1] != nil {
			arg1 = args[1].(Registry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInitializeModule_Init_Call) Return(err error) *MockInitializeModule_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInitializeModule_Init_Call) RunAndReturn(run func(ctx context.Context, registry Registry) error) *MockInitializeModule_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Append(module interface{}, types ...reflect.Type) error {
	// reflect.Type
	_va := make([]any, len(types))
	for _i := range types {
		_va[_i] = types[_i]
	}
	var _ca []any
	_ca = append(_ca, module)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...reflect.Type) error); ok {
		r0 = returnFunc(module, types...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockRegistry_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - module interface{}
//   - types ...reflect.Type
func (_e *MockRegistry_Expecter) Append(module any, types ...any) *MockRegistry_Append_Call {
	return &MockRegistry_Append_Call{Call: _e.mock.On("Append",
		append([]any{module}, types...)...)}
}

func (_c *MockRegistry_Append_Call) Run(run func(module interface{}, types ...reflect.Type)) *MockRegistry_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []reflect.Type
		variadicArgs := make([]reflect.Type, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(reflect.Type)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRegistry_Append_Call) Return(err error) *MockRegistry_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_Append_Call) RunAndReturn(run func(module interface{}, types ...reflect.Type) error) *MockRegistry_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Count(t reflect.Type) int {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) int); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockRegistry_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRegistry_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - t reflect.Type
func (_e *MockRegistry_Expecter) Count(t any) *MockRegistry_Count_Call {
	return &MockRegistry_Count_Call{Call: _e.mock.On("Count", t)}
}

func (_c *MockRegistry_Count_Call) Run(run func(t reflect.Type)) *MockRegistry_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Count_Call) Return(n int) *MockRegistry_Count_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRegistry_Count_Call) RunAndReturn(run func(t reflect.Type) int) *MockRegistry_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Modules provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Modules() []interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modules")
	}

	var r0 []interface{}
	if returnFunc, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	return r0
}

// MockRegistry_Modules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modules'
type MockRegistry_Modules_Call struct {
	*mock.Call
}

// Modules is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) Modules() *MockRegistry_Modules_Call {
	return &MockRegistry_Modules_Call{Call: _e.mock.On("Modules")}
}

func (_c *MockRegistry_Modules_Call) Run(run func()) *MockRegistry_Modules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_Modules_Call) Return(ifaceVals []interface{}) *MockRegistry_Modules_Call {
	_c.Call.Return(ifaceVals)
	return _c
}

func (_c *MockRegistry_Modules_Call) RunAndReturn(run func() []interface{}) *MockRegistry_Modules_Call {
	_c.Call.Return(run)
	return _c
}

// ModulesByType provides a mock function for the type MockRegistry
func (_mock *MockRegistry) ModulesByType(t reflect.Type) ([]interface{}, bool) {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for ModulesByType")
	}

	var r0 []interface{}
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) ([]interface{}, bool)); ok {
		return returnFunc(t)
	}
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) []interface{}); ok {
		r0 = returnFunc(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(reflect.Type) bool); ok {
		r1 = returnFunc(t)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRegistry_ModulesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModulesByType'
type MockRegistry_ModulesByType_Call struct {
	*mock.Call
}

// ModulesByType is a helper method to define mock.On call
//   - t reflect.Type
func (_e *MockRegistry_Expecter) ModulesByType(t any) *MockRegistry_ModulesByType_Call {
	return &MockRegistry_ModulesByType_Call{Call: _e.mock.On("ModulesByType", t)}
}

func (_c *MockRegistry_ModulesByType_Call) Run(run func(t reflect.Type)) *MockRegistry_ModulesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_ModulesByType_Call) Return(ifaceVals []interface{}, b bool) *MockRegistry_ModulesByType_Call {
	_c.Call.Return(ifaceVals, b)
	return _c
}

func (_c *MockRegistry_ModulesByType_Call) RunAndReturn(run func(t reflect.Type) ([]interface{}, bool)) *MockRegistry_ModulesByType_Call {
	_c.Call.Return(run)
	return _c
}

// Traverse provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Traverse(f TraverseFunc[interface{}]) error {
	ret := _mock.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for Traverse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(TraverseFunc[interface{}]) error); ok {
		r0 = returnFunc(f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_Traverse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Traverse'
type MockRegistry_Traverse_Call struct {
	*mock.Call
}

// Traverse is a helper method to define mock.On call
//   - f TraverseFunc[interface{}]
func (_e *MockRegistry_Expecter) Traverse(f any) *MockRegistry_Traverse_Call {
	return &MockRegistry_Traverse_Call{Call: _e.mock.On("Traverse", f)}
}

func (_c *MockRegistry_Traverse_Call) Run(run func(f TraverseFunc[interface{}])) *MockRegistry_Traverse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 TraverseFunc[interface{}]
		if args[0] != nil {
			arg0 = args[0].(TraverseFunc[interface{}])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Traverse_Call) Return(err error) *MockRegistry_Traverse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_Traverse_Call) RunAndReturn(run func(f TraverseFunc[interface{}]) error) *MockRegistry_Traverse_Call {
	_c.Call.Return(run)
	return _c
}

// TraverseByType provides a mock function for the type MockRegistry
func (_mock *MockRegistry) TraverseByType(f TraverseFunc[interface{}], t reflect.Type) error {
	ret := _mock.Called(f, t)

	if len(ret) == 0 {
		panic("no return value specified for TraverseByType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(TraverseFunc[interface{}], reflect.Type) error); ok {
		r0 = returnFunc(f, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_TraverseByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraverseByType'
type MockRegistry_TraverseByType_Call struct {
	*mock.Call
}

// TraverseByType is a helper method to define mock.On call
//   - f TraverseFunc[interface{}]
//   - t reflect.Type
func (_e *MockRegistry_Expecter) TraverseByType(f any, t any) *MockRegistry_TraverseByType_Call {
	return &MockRegistry_TraverseByType_Call{Call: _e.mock.On("TraverseByType", f, t)}
}

func (_c *MockRegistry_TraverseByType_Call) Run(run func(f TraverseFunc[interface{}], t reflect.Type)) *MockRegistry_TraverseByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 TraverseFunc[interface{}]
		if args[0] != nil {
			arg0 = args[0].(TraverseFunc[interface{}])
		}
		var arg1 reflect.Type
		if args[1] != nil {
			arg1 = args[1].(reflect.Type)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_TraverseByType_Call) Return(err error) *MockRegistry_TraverseByType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_TraverseByType_Call) RunAndReturn(run func(f TraverseFunc[interface{}], t reflect.Type) error) *MockRegistry_TraverseByType_Call {
	_c.Call.Return(run)
	return _c
}
