// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ptp

import (
	"context"
	"crypto"
	"crypto/tls"
	"iter"
	"net"
	"pan/pkg/config"
	"pan/pkg/servlet"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBroadcastConfig creates a new instance of MockBroadcastConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcastConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcastConfig {
	mock := &MockBroadcastConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroadcastConfig is an autogenerated mock type for the BroadcastConfig type
type MockBroadcastConfig struct {
	mock.Mock
}

type MockBroadcastConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcastConfig) EXPECT() *MockBroadcastConfig_Expecter {
	return &MockBroadcastConfig_Expecter{mock: &_m.Mock}
}

// Addrs provides a mock function for the type MockBroadcastConfig
func (_mock *MockBroadcastConfig) Addrs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addrs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockBroadcastConfig_Addrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addrs'
type MockBroadcastConfig_Addrs_Call struct {
	*mock.Call
}

// Addrs is a helper method to define mock.On call
func (_e *MockBroadcastConfig_Expecter) Addrs() *MockBroadcastConfig_Addrs_Call {
	return &MockBroadcastConfig_Addrs_Call{Call: _e.mock.On("Addrs")}
}

func (_c *MockBroadcastConfig_Addrs_Call) Run(run func()) *MockBroadcastConfig_Addrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfig_Addrs_Call) Return(strings []string) *MockBroadcastConfig_Addrs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockBroadcastConfig_Addrs_Call) RunAndReturn(run func() []string) *MockBroadcastConfig_Addrs_Call {
	_c.Call.Return(run)
	return _c
}

// DeliverMaxSize provides a mock function for the type MockBroadcastConfig
func (_mock *MockBroadcastConfig) DeliverMaxSize() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeliverMaxSize")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockBroadcastConfig_DeliverMaxSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeliverMaxSize'
type MockBroadcastConfig_DeliverMaxSize_Call struct {
	*mock.Call
}

// DeliverMaxSize is a helper method to define mock.On call
func (_e *MockBroadcastConfig_Expecter) DeliverMaxSize() *MockBroadcastConfig_DeliverMaxSize_Call {
	return &MockBroadcastConfig_DeliverMaxSize_Call{Call: _e.mock.On("DeliverMaxSize")}
}

func (_c *MockBroadcastConfig_DeliverMaxSize_Call) Run(run func()) *MockBroadcastConfig_DeliverMaxSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfig_DeliverMaxSize_Call) Return(n int) *MockBroadcastConfig_DeliverMaxSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBroadcastConfig_DeliverMaxSize_Call) RunAndReturn(run func() int) *MockBroadcastConfig_DeliverMaxSize_Call {
	_c.Call.Return(run)
	return _c
}

// IPv6Enabled provides a mock function for the type MockBroadcastConfig
func (_mock *MockBroadcastConfig) IPv6Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IPv6Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBroadcastConfig_IPv6Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPv6Enabled'
type MockBroadcastConfig_IPv6Enabled_Call struct {
	*mock.Call
}

// IPv6Enabled is a helper method to define mock.On call
func (_e *MockBroadcastConfig_Expecter) IPv6Enabled() *MockBroadcastConfig_IPv6Enabled_Call {
	return &MockBroadcastConfig_IPv6Enabled_Call{Call: _e.mock.On("IPv6Enabled")}
}

func (_c *MockBroadcastConfig_IPv6Enabled_Call) Run(run func()) *MockBroadcastConfig_IPv6Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfig_IPv6Enabled_Call) Return(b bool) *MockBroadcastConfig_IPv6Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBroadcastConfig_IPv6Enabled_Call) RunAndReturn(run func() bool) *MockBroadcastConfig_IPv6Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// IPv6ZoneList provides a mock function for the type MockBroadcastConfig
func (_mock *MockBroadcastConfig) IPv6ZoneList() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IPv6ZoneList")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockBroadcastConfig_IPv6ZoneList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPv6ZoneList'
type MockBroadcastConfig_IPv6ZoneList_Call struct {
	*mock.Call
}

// IPv6ZoneList is a helper method to define mock.On call
func (_e *MockBroadcastConfig_Expecter) IPv6ZoneList() *MockBroadcastConfig_IPv6ZoneList_Call {
	return &MockBroadcastConfig_IPv6ZoneList_Call{Call: _e.mock.On("IPv6ZoneList")}
}

func (_c *MockBroadcastConfig_IPv6ZoneList_Call) Run(run func()) *MockBroadcastConfig_IPv6ZoneList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfig_IPv6ZoneList_Call) Return(strings []string) *MockBroadcastConfig_IPv6ZoneList_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockBroadcastConfig_IPv6ZoneList_Call) RunAndReturn(run func() []string) *MockBroadcastConfig_IPv6ZoneList_Call {
	_c.Call.Return(run)
	return _c
}

// Interfaces provides a mock function for the type MockBroadcastConfig
func (_mock *MockBroadcastConfig) Interfaces() []BroadcastInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []BroadcastInterface
	if returnFunc, ok := ret.Get(0).(func() []BroadcastInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BroadcastInterface)
		}
	}
	return r0
}

// MockBroadcastConfig_Interfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Interfaces'
type MockBroadcastConfig_Interfaces_Call struct {
	*mock.Call
}

// Interfaces is a helper method to define mock.On call
func (_e *MockBroadcastConfig_Expecter) Interfaces() *MockBroadcastConfig_Interfaces_Call {
	return &MockBroadcastConfig_Interfaces_Call{Call: _e.mock.On("Interfaces")}
}

func (_c *MockBroadcastConfig_Interfaces_Call) Run(run func()) *MockBroadcastConfig_Interfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfig_Interfaces_Call) Return(broadcastInterfaces []BroadcastInterface) *MockBroadcastConfig_Interfaces_Call {
	_c.Call.Return(broadcastInterfaces)
	return _c
}

func (_c *MockBroadcastConfig_Interfaces_Call) RunAndReturn(run func() []BroadcastInterface) *MockBroadcastConfig_Interfaces_Call {
	_c.Call.Return(run)
	return _c
}

// MTU provides a mock function for the type MockBroadcastConfig
func (_mock *MockBroadcastConfig) MTU() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MTU")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockBroadcastConfig_MTU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MTU'
type MockBroadcastConfig_MTU_Call struct {
	*mock.Call
}

// MTU is a helper method to define mock.On call
func (_e *MockBroadcastConfig_Expecter) MTU() *MockBroadcastConfig_MTU_Call {
	return &MockBroadcastConfig_MTU_Call{Call: _e.mock.On("MTU")}
}

func (_c *MockBroadcastConfig_MTU_Call) Run(run func()) *MockBroadcastConfig_MTU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfig_MTU_Call) Return(n int) *MockBroadcastConfig_MTU_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBroadcastConfig_MTU_Call) RunAndReturn(run func() int) *MockBroadcastConfig_MTU_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBroadcastConfigListener creates a new instance of MockBroadcastConfigListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcastConfigListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcastConfigListener {
	mock := &MockBroadcastConfigListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroadcastConfigListener is an autogenerated mock type for the BroadcastConfigListener type
type MockBroadcastConfigListener struct {
	mock.Mock
}

type MockBroadcastConfigListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcastConfigListener) EXPECT() *MockBroadcastConfigListener_Expecter {
	return &MockBroadcastConfigListener_Expecter{mock: &_m.Mock}
}

// OnConfigUpdated provides a mock function for the type MockBroadcastConfigListener
func (_mock *MockBroadcastConfigListener) OnConfigUpdated(config BroadcastConfig) {
	_mock.Called(config)
	return
}

// MockBroadcastConfigListener_OnConfigUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigUpdated'
type MockBroadcastConfigListener_OnConfigUpdated_Call struct {
	*mock.Call
}

// OnConfigUpdated is a helper method to define mock.On call
//   - config BroadcastConfig
func (_e *MockBroadcastConfigListener_Expecter) OnConfigUpdated(config any) *MockBroadcastConfigListener_OnConfigUpdated_Call {
	return &MockBroadcastConfigListener_OnConfigUpdated_Call{Call: _e.mock.On("OnConfigUpdated", config)}
}

func (_c *MockBroadcastConfigListener_OnConfigUpdated_Call) Run(run func(config BroadcastConfig)) *MockBroadcastConfigListener_OnConfigUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 BroadcastConfig
		if args[0] != nil {
			arg0 = args[0].(BroadcastConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBroadcastConfigListener_OnConfigUpdated_Call) Return() *MockBroadcastConfigListener_OnConfigUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroadcastConfigListener_OnConfigUpdated_Call) RunAndReturn(run func(config BroadcastConfig)) *MockBroadcastConfigListener_OnConfigUpdated_Call {
	_c.Run(run)
	return _c
}

// NewMockBroadcastConfigurer creates a new instance of MockBroadcastConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcastConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcastConfigurer {
	mock := &MockBroadcastConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroadcastConfigurer is an autogenerated mock type for the BroadcastConfigurer type
type MockBroadcastConfigurer struct {
	mock.Mock
}

type MockBroadcastConfigurer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcastConfigurer) EXPECT() *MockBroadcastConfigurer_Expecter {
	return &MockBroadcastConfigurer_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockBroadcastConfigurer
func (_mock *MockBroadcastConfigurer) Config() BroadcastConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 BroadcastConfig
	if returnFunc, ok := ret.Get(0).(func() BroadcastConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BroadcastConfig)
		}
	}
	return r0
}

// MockBroadcastConfigurer_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockBroadcastConfigurer_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockBroadcastConfigurer_Expecter) Config() *MockBroadcastConfigurer_Config_Call {
	return &MockBroadcastConfigurer_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockBroadcastConfigurer_Config_Call) Run(run func()) *MockBroadcastConfigurer_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfigurer_Config_Call) Return(broadcastConfig BroadcastConfig) *MockBroadcastConfigurer_Config_Call {
	_c.Call.Return(broadcastConfig)
	return _c
}

func (_c *MockBroadcastConfigurer_Config_Call) RunAndReturn(run func() BroadcastConfig) *MockBroadcastConfigurer_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigListeners provides a mock function for the type MockBroadcastConfigurer
func (_mock *MockBroadcastConfigurer) ConfigListeners() []config.ConfigurerListener[BroadcastConfig] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigListeners")
	}

	var r0 []config.ConfigurerListener[BroadcastConfig]
	if returnFunc, ok := ret.Get(0).(func() []config.ConfigurerListener[BroadcastConfig]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ConfigurerListener[BroadcastConfig])
		}
	}
	return r0
}

// MockBroadcastConfigurer_ConfigListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigListeners'
type MockBroadcastConfigurer_ConfigListeners_Call struct {
	*mock.Call
}

// ConfigListeners is a helper method to define mock.On call
func (_e *MockBroadcastConfigurer_Expecter) ConfigListeners() *MockBroadcastConfigurer_ConfigListeners_Call {
	return &MockBroadcastConfigurer_ConfigListeners_Call{Call: _e.mock.On("ConfigListeners")}
}

func (_c *MockBroadcastConfigurer_ConfigListeners_Call) Run(run func()) *MockBroadcastConfigurer_ConfigListeners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroadcastConfigurer_ConfigListeners_Call) Return(configurerListeners []config.ConfigurerListener[BroadcastConfig]) *MockBroadcastConfigurer_ConfigListeners_Call {
	_c.Call.Return(configurerListeners)
	return _c
}

func (_c *MockBroadcastConfigurer_ConfigListeners_Call) RunAndReturn(run func() []config.ConfigurerListener[BroadcastConfig]) *MockBroadcastConfigurer_ConfigListeners_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type MockBroadcastConfigurer
func (_mock *MockBroadcastConfigurer) Configure(config1 BroadcastConfig) error {
	ret := _mock.Called(config1)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(BroadcastConfig) error); ok {
		r0 = returnFunc(config1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroadcastConfigurer_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockBroadcastConfigurer_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - config1 BroadcastConfig
func (_e *MockBroadcastConfigurer_Expecter) Configure(config1 any) *MockBroadcastConfigurer_Configure_Call {
	return &MockBroadcastConfigurer_Configure_Call{Call: _e.mock.On("Configure", config1)}
}

func (_c *MockBroadcastConfigurer_Configure_Call) Run(run func(config1 BroadcastConfig)) *MockBroadcastConfigurer_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 BroadcastConfig
		if args[0] != nil {
			arg0 = args[0].(BroadcastConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBroadcastConfigurer_Configure_Call) Return(err error) *MockBroadcastConfigurer_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroadcastConfigurer_Configure_Call) RunAndReturn(run func(config1 BroadcastConfig) error) *MockBroadcastConfigurer_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockBroadcastConfigurer
func (_mock *MockBroadcastConfigurer) Subscribe(listener config.ConfigurerListener[BroadcastConfig]) {
	_mock.Called(listener)
	return
}

// MockBroadcastConfigurer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBroadcastConfigurer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[BroadcastConfig]
func (_e *MockBroadcastConfigurer_Expecter) Subscribe(listener any) *MockBroadcastConfigurer_Subscribe_Call {
	return &MockBroadcastConfigurer_Subscribe_Call{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *MockBroadcastConfigurer_Subscribe_Call) Run(run func(listener config.ConfigurerListener[BroadcastConfig])) *MockBroadcastConfigurer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[BroadcastConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[BroadcastConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBroadcastConfigurer_Subscribe_Call) Return() *MockBroadcastConfigurer_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroadcastConfigurer_Subscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[BroadcastConfig])) *MockBroadcastConfigurer_Subscribe_Call {
	_c.Run(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockBroadcastConfigurer
func (_mock *MockBroadcastConfigurer) Unsubscribe(listener config.ConfigurerListener[BroadcastConfig]) {
	_mock.Called(listener)
	return
}

// MockBroadcastConfigurer_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockBroadcastConfigurer_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[BroadcastConfig]
func (_e *MockBroadcastConfigurer_Expecter) Unsubscribe(listener any) *MockBroadcastConfigurer_Unsubscribe_Call {
	return &MockBroadcastConfigurer_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", listener)}
}

func (_c *MockBroadcastConfigurer_Unsubscribe_Call) Run(run func(listener config.ConfigurerListener[BroadcastConfig])) *MockBroadcastConfigurer_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[BroadcastConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[BroadcastConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBroadcastConfigurer_Unsubscribe_Call) Return() *MockBroadcastConfigurer_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroadcastConfigurer_Unsubscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[BroadcastConfig])) *MockBroadcastConfigurer_Unsubscribe_Call {
	_c.Run(run)
	return _c
}

// NewMockPacketConn creates a new instance of MockPacketConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPacketConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPacketConn {
	mock := &MockPacketConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPacketConn is an autogenerated mock type for the PacketConn type
type MockPacketConn struct {
	mock.Mock
}

type MockPacketConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPacketConn) EXPECT() *MockPacketConn_Expecter {
	return &MockPacketConn_Expecter{mock: &_m.Mock}
}

// JoinGroup provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) JoinGroup(ifi *net.Interface, group net.Addr) error {
	ret := _mock.Called(ifi, group)

	if len(ret) == 0 {
		panic("no return value specified for JoinGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.Interface, net.Addr) error); ok {
		r0 = returnFunc(ifi, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_JoinGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinGroup'
type MockPacketConn_JoinGroup_Call struct {
	*mock.Call
}

// JoinGroup is a helper method to define mock.On call
//   - ifi *net.Interface
//   - group net.Addr
func (_e *MockPacketConn_Expecter) JoinGroup(ifi any, group any) *MockPacketConn_JoinGroup_Call {
	return &MockPacketConn_JoinGroup_Call{Call: _e.mock.On("JoinGroup", ifi, group)}
}

func (_c *MockPacketConn_JoinGroup_Call) Run(run func(ifi *net.Interface, group net.Addr)) *MockPacketConn_JoinGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.Interface
		if args[0] != nil {
			arg0 = args[0].(*net.Interface)
		}
		var arg1 net.Addr
		if args[1] != nil {
			arg1 = args[1].(net.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPacketConn_JoinGroup_Call) Return(err error) *MockPacketConn_JoinGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_JoinGroup_Call) RunAndReturn(run func(ifi *net.Interface, group net.Addr) error) *MockPacketConn_JoinGroup_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveGroup provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) LeaveGroup(ifi *net.Interface, group net.Addr) error {
	ret := _mock.Called(ifi, group)

	if len(ret) == 0 {
		panic("no return value specified for LeaveGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.Interface, net.Addr) error); ok {
		r0 = returnFunc(ifi, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_LeaveGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveGroup'
type MockPacketConn_LeaveGroup_Call struct {
	*mock.Call
}

// LeaveGroup is a helper method to define mock.On call
//   - ifi *net.Interface
//   - group net.Addr
func (_e *MockPacketConn_Expecter) LeaveGroup(ifi any, group any) *MockPacketConn_LeaveGroup_Call {
	return &MockPacketConn_LeaveGroup_Call{Call: _e.mock.On("LeaveGroup", ifi, group)}
}

func (_c *MockPacketConn_LeaveGroup_Call) Run(run func(ifi *net.Interface, group net.Addr)) *MockPacketConn_LeaveGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.Interface
		if args[0] != nil {
			arg0 = args[0].(*net.Interface)
		}
		var arg1 net.Addr
		if args[1] != nil {
			arg1 = args[1].(net.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPacketConn_LeaveGroup_Call) Return(err error) *MockPacketConn_LeaveGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_LeaveGroup_Call) RunAndReturn(run func(ifi *net.Interface, group net.Addr) error) *MockPacketConn_LeaveGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBroadcastServeModule creates a new instance of MockBroadcastServeModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcastServeModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcastServeModule {
	mock := &MockBroadcastServeModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroadcastServeModule is an autogenerated mock type for the BroadcastServeModule type
type MockBroadcastServeModule struct {
	mock.Mock
}

type MockBroadcastServeModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcastServeModule) EXPECT() *MockBroadcastServeModule_Expecter {
	return &MockBroadcastServeModule_Expecter{mock: &_m.Mock}
}

// ServeBroadcast provides a mock function for the type MockBroadcastServeModule
func (_mock *MockBroadcastServeModule) ServeBroadcast(bytes []byte, s string) error {
	ret := _mock.Called(bytes, s)

	if len(ret) == 0 {
		panic("no return value specified for ServeBroadcast")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = returnFunc(bytes, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBroadcastServeModule_ServeBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeBroadcast'
type MockBroadcastServeModule_ServeBroadcast_Call struct {
	*mock.Call
}

// ServeBroadcast is a helper method to define mock.On call
//   - bytes []byte
//   - s string
func (_e *MockBroadcastServeModule_Expecter) ServeBroadcast(bytes any, s any) *MockBroadcastServeModule_ServeBroadcast_Call {
	return &MockBroadcastServeModule_ServeBroadcast_Call{Call: _e.mock.On("ServeBroadcast", bytes, s)}
}

func (_c *MockBroadcastServeModule_ServeBroadcast_Call) Run(run func(bytes []byte, s string)) *MockBroadcastServeModule_ServeBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroadcastServeModule_ServeBroadcast_Call) Return(err error) *MockBroadcastServeModule_ServeBroadcast_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBroadcastServeModule_ServeBroadcast_Call) RunAndReturn(run func(bytes []byte, s string) error) *MockBroadcastServeModule_ServeBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActionSession creates a new instance of MockActionSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActionSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActionSession {
	mock := &MockActionSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActionSession is an autogenerated mock type for the ActionSession type
type MockActionSession struct {
	mock.Mock
}

type MockActionSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActionSession) EXPECT() *MockActionSession_Expecter {
	return &MockActionSession_Expecter{mock: &_m.Mock}
}

// Header provides a mock function for the type MockActionSession
func (_mock *MockActionSession) Header(key []byte) ([]byte, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActionSession_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockActionSession_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
//   - key []byte
func (_e *MockActionSession_Expecter) Header(key any) *MockActionSession_Header_Call {
	return &MockActionSession_Header_Call{Call: _e.mock.On("Header", key)}
}

func (_c *MockActionSession_Header_Call) Run(run func(key []byte)) *MockActionSession_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActionSession_Header_Call) Return(bytes []byte, b bool) *MockActionSession_Header_Call {
	_c.Call.Return(bytes, b)
	return _c
}

func (_c *MockActionSession_Header_Call) RunAndReturn(run func(key []byte) ([]byte, bool)) *MockActionSession_Header_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerStream creates a new instance of MockPeerStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerStream {
	mock := &MockPeerStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerStream is an autogenerated mock type for the PeerStream type
type MockPeerStream struct {
	mock.Mock
}

type MockPeerStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerStream) EXPECT() *MockPeerStream_Expecter {
	return &MockPeerStream_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPeerStream
func (_mock *MockPeerStream) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerStream_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPeerStream_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPeerStream_Expecter) Close() *MockPeerStream_Close_Call {
	return &MockPeerStream_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPeerStream_Close_Call) Run(run func()) *MockPeerStream_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerStream_Close_Call) Return(err error) *MockPeerStream_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerStream_Close_Call) RunAndReturn(run func() error) *MockPeerStream_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockPeerStream
func (_mock *MockPeerStream) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerStream_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockPeerStream_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockPeerStream_Expecter) Read(p any) *MockPeerStream_Read_Call {
	return &MockPeerStream_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *MockPeerStream_Read_Call) Run(run func(p []byte)) *MockPeerStream_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerStream_Read_Call) Return(n int, err error) *MockPeerStream_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPeerStream_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *MockPeerStream_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockPeerStream
func (_mock *MockPeerStream) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerStream_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockPeerStream_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockPeerStream_Expecter) Write(p any) *MockPeerStream_Write_Call {
	return &MockPeerStream_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockPeerStream_Write_Call) Run(run func(p []byte)) *MockPeerStream_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerStream_Write_Call) Return(n int, err error) *MockPeerStream_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPeerStream_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockPeerStream_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerConn creates a new instance of MockPeerConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerConn {
	mock := &MockPeerConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerConn is an autogenerated mock type for the PeerConn type
type MockPeerConn struct {
	mock.Mock
}

type MockPeerConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerConn) EXPECT() *MockPeerConn_Expecter {
	return &MockPeerConn_Expecter{mock: &_m.Mock}
}

// AcceptStream provides a mock function for the type MockPeerConn
func (_mock *MockPeerConn) AcceptStream(context1 context.Context) (PeerStream, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for AcceptStream")
	}

	var r0 PeerStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (PeerStream, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) PeerStream); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerConn_AcceptStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptStream'
type MockPeerConn_AcceptStream_Call struct {
	*mock.Call
}

// AcceptStream is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPeerConn_Expecter) AcceptStream(context1 any) *MockPeerConn_AcceptStream_Call {
	return &MockPeerConn_AcceptStream_Call{Call: _e.mock.On("AcceptStream", context1)}
}

func (_c *MockPeerConn_AcceptStream_Call) Run(run func(context1 context.Context)) *MockPeerConn_AcceptStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerConn_AcceptStream_Call) Return(peerStream PeerStream, err error) *MockPeerConn_AcceptStream_Call {
	_c.Call.Return(peerStream, err)
	return _c
}

func (_c *MockPeerConn_AcceptStream_Call) RunAndReturn(run func(context1 context.Context) (PeerStream, error)) *MockPeerConn_AcceptStream_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockPeerConn
func (_mock *MockPeerConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPeerConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPeerConn_Expecter) Close() *MockPeerConn_Close_Call {
	return &MockPeerConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPeerConn_Close_Call) Run(run func()) *MockPeerConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerConn_Close_Call) Return(err error) *MockPeerConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerConn_Close_Call) RunAndReturn(run func() error) *MockPeerConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// OpenStream provides a mock function for the type MockPeerConn
func (_mock *MockPeerConn) OpenStream(context1 context.Context) (PeerStream, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for OpenStream")
	}

	var r0 PeerStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (PeerStream, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) PeerStream); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerConn_OpenStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenStream'
type MockPeerConn_OpenStream_Call struct {
	*mock.Call
}

// OpenStream is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPeerConn_Expecter) OpenStream(context1 any) *MockPeerConn_OpenStream_Call {
	return &MockPeerConn_OpenStream_Call{Call: _e.mock.On("OpenStream", context1)}
}

func (_c *MockPeerConn_OpenStream_Call) Run(run func(context1 context.Context)) *MockPeerConn_OpenStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerConn_OpenStream_Call) Return(peerStream PeerStream, err error) *MockPeerConn_OpenStream_Call {
	_c.Call.Return(peerStream, err)
	return _c
}

func (_c *MockPeerConn_OpenStream_Call) RunAndReturn(run func(context1 context.Context) (PeerStream, error)) *MockPeerConn_OpenStream_Call {
	_c.Call.Return(run)
	return _c
}

// PeerID provides a mock function for the type MockPeerConn
func (_mock *MockPeerConn) PeerID() PeerID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PeerID")
	}

	var r0 PeerID
	if returnFunc, ok := ret.Get(0).(func() PeerID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerID)
		}
	}
	return r0
}

// MockPeerConn_PeerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerID'
type MockPeerConn_PeerID_Call struct {
	*mock.Call
}

// PeerID is a helper method to define mock.On call
func (_e *MockPeerConn_Expecter) PeerID() *MockPeerConn_PeerID_Call {
	return &MockPeerConn_PeerID_Call{Call: _e.mock.On("PeerID")}
}

func (_c *MockPeerConn_PeerID_Call) Run(run func()) *MockPeerConn_PeerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerConn_PeerID_Call) Return(v PeerID) *MockPeerConn_PeerID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPeerConn_PeerID_Call) RunAndReturn(run func() PeerID) *MockPeerConn_PeerID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCodeError creates a new instance of MockCodeError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeError {
	mock := &MockCodeError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodeError is an autogenerated mock type for the CodeError type
type MockCodeError struct {
	mock.Mock
}

type MockCodeError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeError) EXPECT() *MockCodeError_Expecter {
	return &MockCodeError_Expecter{mock: &_m.Mock}
}

// Code provides a mock function for the type MockCodeError
func (_mock *MockCodeError) Code() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCodeError_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type MockCodeError_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *MockCodeError_Expecter) Code() *MockCodeError_Code_Call {
	return &MockCodeError_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *MockCodeError_Code_Call) Run(run func()) *MockCodeError_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodeError_Code_Call) Return(n int) *MockCodeError_Code_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodeError_Code_Call) RunAndReturn(run func() int) *MockCodeError_Code_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerGuardGuide creates a new instance of MockPeerGuardGuide. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerGuardGuide(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerGuardGuide {
	mock := &MockPeerGuardGuide{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerGuardGuide is an autogenerated mock type for the PeerGuardGuide type
type MockPeerGuardGuide struct {
	mock.Mock
}

type MockPeerGuardGuide_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerGuardGuide) EXPECT() *MockPeerGuardGuide_Expecter {
	return &MockPeerGuardGuide_Expecter{mock: &_m.Mock}
}

// IsAccessible provides a mock function for the type MockPeerGuardGuide
func (_mock *MockPeerGuardGuide) IsAccessible(v PeerID) bool {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for IsAccessible")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(PeerID) bool); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerGuardGuide_IsAccessible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccessible'
type MockPeerGuardGuide_IsAccessible_Call struct {
	*mock.Call
}

// IsAccessible is a helper method to define mock.On call
//   - v PeerID
func (_e *MockPeerGuardGuide_Expecter) IsAccessible(v any) *MockPeerGuardGuide_IsAccessible_Call {
	return &MockPeerGuardGuide_IsAccessible_Call{Call: _e.mock.On("IsAccessible", v)}
}

func (_c *MockPeerGuardGuide_IsAccessible_Call) Run(run func(v PeerID)) *MockPeerGuardGuide_IsAccessible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PeerID
		if args[0] != nil {
			arg0 = args[0].(PeerID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerGuardGuide_IsAccessible_Call) Return(b bool) *MockPeerGuardGuide_IsAccessible_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerGuardGuide_IsAccessible_Call) RunAndReturn(run func(v PeerID) bool) *MockPeerGuardGuide_IsAccessible_Call {
	_c.Call.Return(run)
	return _c
}

// IsDenied provides a mock function for the type MockPeerGuardGuide
func (_mock *MockPeerGuardGuide) IsDenied(v PeerID) bool {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for IsDenied")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(PeerID) bool); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPeerGuardGuide_IsDenied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDenied'
type MockPeerGuardGuide_IsDenied_Call struct {
	*mock.Call
}

// IsDenied is a helper method to define mock.On call
//   - v PeerID
func (_e *MockPeerGuardGuide_Expecter) IsDenied(v any) *MockPeerGuardGuide_IsDenied_Call {
	return &MockPeerGuardGuide_IsDenied_Call{Call: _e.mock.On("IsDenied", v)}
}

func (_c *MockPeerGuardGuide_IsDenied_Call) Run(run func(v PeerID)) *MockPeerGuardGuide_IsDenied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PeerID
		if args[0] != nil {
			arg0 = args[0].(PeerID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerGuardGuide_IsDenied_Call) Return(b bool) *MockPeerGuardGuide_IsDenied_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPeerGuardGuide_IsDenied_Call) RunAndReturn(run func(v PeerID) bool) *MockPeerGuardGuide_IsDenied_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerAppModule creates a new instance of MockPeerAppModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerAppModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerAppModule {
	mock := &MockPeerAppModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerAppModule is an autogenerated mock type for the PeerAppModule type
type MockPeerAppModule struct {
	mock.Mock
}

type MockPeerAppModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerAppModule) EXPECT() *MockPeerAppModule_Expecter {
	return &MockPeerAppModule_Expecter{mock: &_m.Mock}
}

// SetupToPeer provides a mock function for the type MockPeerAppModule
func (_mock *MockPeerAppModule) SetupToPeer(v PeerServlet) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for SetupToPeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(PeerServlet) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerAppModule_SetupToPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToPeer'
type MockPeerAppModule_SetupToPeer_Call struct {
	*mock.Call
}

// SetupToPeer is a helper method to define mock.On call
//   - v PeerServlet
func (_e *MockPeerAppModule_Expecter) SetupToPeer(v any) *MockPeerAppModule_SetupToPeer_Call {
	return &MockPeerAppModule_SetupToPeer_Call{Call: _e.mock.On("SetupToPeer", v)}
}

func (_c *MockPeerAppModule_SetupToPeer_Call) Run(run func(v PeerServlet)) *MockPeerAppModule_SetupToPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PeerServlet
		if args[0] != nil {
			arg0 = args[0].(PeerServlet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerAppModule_SetupToPeer_Call) Return(err error) *MockPeerAppModule_SetupToPeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerAppModule_SetupToPeer_Call) RunAndReturn(run func(v PeerServlet) error) *MockPeerAppModule_SetupToPeer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerTopic creates a new instance of MockPeerTopic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerTopic(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerTopic {
	mock := &MockPeerTopic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerTopic is an autogenerated mock type for the PeerTopic type
type MockPeerTopic struct {
	mock.Mock
}

type MockPeerTopic_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerTopic) EXPECT() *MockPeerTopic_Expecter {
	return &MockPeerTopic_Expecter{mock: &_m.Mock}
}

// SetupToPeer provides a mock function for the type MockPeerTopic
func (_mock *MockPeerTopic) SetupToPeer(v PeerServletRouter) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for SetupToPeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(PeerServletRouter) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerTopic_SetupToPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToPeer'
type MockPeerTopic_SetupToPeer_Call struct {
	*mock.Call
}

// SetupToPeer is a helper method to define mock.On call
//   - v PeerServletRouter
func (_e *MockPeerTopic_Expecter) SetupToPeer(v any) *MockPeerTopic_SetupToPeer_Call {
	return &MockPeerTopic_SetupToPeer_Call{Call: _e.mock.On("SetupToPeer", v)}
}

func (_c *MockPeerTopic_SetupToPeer_Call) Run(run func(v PeerServletRouter)) *MockPeerTopic_SetupToPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PeerServletRouter
		if args[0] != nil {
			arg0 = args[0].(PeerServletRouter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerTopic_SetupToPeer_Call) Return(err error) *MockPeerTopic_SetupToPeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerTopic_SetupToPeer_Call) RunAndReturn(run func(v PeerServletRouter) error) *MockPeerTopic_SetupToPeer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerTopicProvider creates a new instance of MockPeerTopicProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerTopicProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerTopicProvider {
	mock := &MockPeerTopicProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerTopicProvider is an autogenerated mock type for the PeerTopicProvider type
type MockPeerTopicProvider struct {
	mock.Mock
}

type MockPeerTopicProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerTopicProvider) EXPECT() *MockPeerTopicProvider_Expecter {
	return &MockPeerTopicProvider_Expecter{mock: &_m.Mock}
}

// PeerTopics provides a mock function for the type MockPeerTopicProvider
func (_mock *MockPeerTopicProvider) PeerTopics() []PeerTopic {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PeerTopics")
	}

	var r0 []PeerTopic
	if returnFunc, ok := ret.Get(0).(func() []PeerTopic); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PeerTopic)
		}
	}
	return r0
}

// MockPeerTopicProvider_PeerTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerTopics'
type MockPeerTopicProvider_PeerTopics_Call struct {
	*mock.Call
}

// PeerTopics is a helper method to define mock.On call
func (_e *MockPeerTopicProvider_Expecter) PeerTopics() *MockPeerTopicProvider_PeerTopics_Call {
	return &MockPeerTopicProvider_PeerTopics_Call{Call: _e.mock.On("PeerTopics")}
}

func (_c *MockPeerTopicProvider_PeerTopics_Call) Run(run func()) *MockPeerTopicProvider_PeerTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerTopicProvider_PeerTopics_Call) Return(peerTopics []PeerTopic) *MockPeerTopicProvider_PeerTopics_Call {
	_c.Call.Return(peerTopics)
	return _c
}

func (_c *MockPeerTopicProvider_PeerTopics_Call) RunAndReturn(run func() []PeerTopic) *MockPeerTopicProvider_PeerTopics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerRouteModule creates a new instance of MockPeerRouteModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerRouteModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerRouteModule {
	mock := &MockPeerRouteModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerRouteModule is an autogenerated mock type for the PeerRouteModule type
type MockPeerRouteModule struct {
	mock.Mock
}

type MockPeerRouteModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerRouteModule) EXPECT() *MockPeerRouteModule_Expecter {
	return &MockPeerRouteModule_Expecter{mock: &_m.Mock}
}

// PeerRouteScope provides a mock function for the type MockPeerRouteModule
func (_mock *MockPeerRouteModule) PeerRouteScope() PeerServletScope {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PeerRouteScope")
	}

	var r0 PeerServletScope
	if returnFunc, ok := ret.Get(0).(func() PeerServletScope); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerServletScope)
		}
	}
	return r0
}

// MockPeerRouteModule_PeerRouteScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerRouteScope'
type MockPeerRouteModule_PeerRouteScope_Call struct {
	*mock.Call
}

// PeerRouteScope is a helper method to define mock.On call
func (_e *MockPeerRouteModule_Expecter) PeerRouteScope() *MockPeerRouteModule_PeerRouteScope_Call {
	return &MockPeerRouteModule_PeerRouteScope_Call{Call: _e.mock.On("PeerRouteScope")}
}

func (_c *MockPeerRouteModule_PeerRouteScope_Call) Run(run func()) *MockPeerRouteModule_PeerRouteScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerRouteModule_PeerRouteScope_Call) Return(v PeerServletScope) *MockPeerRouteModule_PeerRouteScope_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPeerRouteModule_PeerRouteScope_Call) RunAndReturn(run func() PeerServletScope) *MockPeerRouteModule_PeerRouteScope_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerNetwork creates a new instance of MockPeerNetwork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerNetwork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerNetwork {
	mock := &MockPeerNetwork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerNetwork is an autogenerated mock type for the PeerNetwork type
type MockPeerNetwork struct {
	mock.Mock
}

type MockPeerNetwork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerNetwork) EXPECT() *MockPeerNetwork_Expecter {
	return &MockPeerNetwork_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockPeerNetwork
func (_mock *MockPeerNetwork) Connect(context1 context.Context, v PeerID) (PeerConn, error) {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 PeerConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerID) (PeerConn, error)); ok {
		return returnFunc(context1, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerID) PeerConn); ok {
		r0 = returnFunc(context1, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PeerID) error); ok {
		r1 = returnFunc(context1, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerNetwork_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockPeerNetwork_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - context1 context.Context
//   - v PeerID
func (_e *MockPeerNetwork_Expecter) Connect(context1 any, v any) *MockPeerNetwork_Connect_Call {
	return &MockPeerNetwork_Connect_Call{Call: _e.mock.On("Connect", context1, v)}
}

func (_c *MockPeerNetwork_Connect_Call) Run(run func(context1 context.Context, v PeerID)) *MockPeerNetwork_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PeerID
		if args[1] != nil {
			arg1 = args[1].(PeerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerNetwork_Connect_Call) Return(peerConn PeerConn, err error) *MockPeerNetwork_Connect_Call {
	_c.Call.Return(peerConn, err)
	return _c
}

func (_c *MockPeerNetwork_Connect_Call) RunAndReturn(run func(context1 context.Context, v PeerID) (PeerConn, error)) *MockPeerNetwork_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Reuse provides a mock function for the type MockPeerNetwork
func (_mock *MockPeerNetwork) Reuse(peerConn PeerConn) error {
	ret := _mock.Called(peerConn)

	if len(ret) == 0 {
		panic("no return value specified for Reuse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(PeerConn) error); ok {
		r0 = returnFunc(peerConn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerNetwork_Reuse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reuse'
type MockPeerNetwork_Reuse_Call struct {
	*mock.Call
}

// Reuse is a helper method to define mock.On call
//   - peerConn PeerConn
func (_e *MockPeerNetwork_Expecter) Reuse(peerConn any) *MockPeerNetwork_Reuse_Call {
	return &MockPeerNetwork_Reuse_Call{Call: _e.mock.On("Reuse", peerConn)}
}

func (_c *MockPeerNetwork_Reuse_Call) Run(run func(peerConn PeerConn)) *MockPeerNetwork_Reuse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PeerConn
		if args[0] != nil {
			arg0 = args[0].(PeerConn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerNetwork_Reuse_Call) Return(err error) *MockPeerNetwork_Reuse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerNetwork_Reuse_Call) RunAndReturn(run func(peerConn PeerConn) error) *MockPeerNetwork_Reuse_Call {
	_c.Call.Return(run)
	return _c
}

// RoundTrip provides a mock function for the type MockPeerNetwork
func (_mock *MockPeerNetwork) RoundTrip(context1 context.Context, v PeerID) (PeerStream, error) {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for RoundTrip")
	}

	var r0 PeerStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerID) (PeerStream, error)); ok {
		return returnFunc(context1, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerID) PeerStream); ok {
		r0 = returnFunc(context1, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PeerID) error); ok {
		r1 = returnFunc(context1, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPeerNetwork_RoundTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoundTrip'
type MockPeerNetwork_RoundTrip_Call struct {
	*mock.Call
}

// RoundTrip is a helper method to define mock.On call
//   - context1 context.Context
//   - v PeerID
func (_e *MockPeerNetwork_Expecter) RoundTrip(context1 any, v any) *MockPeerNetwork_RoundTrip_Call {
	return &MockPeerNetwork_RoundTrip_Call{Call: _e.mock.On("RoundTrip", context1, v)}
}

func (_c *MockPeerNetwork_RoundTrip_Call) Run(run func(context1 context.Context, v PeerID)) *MockPeerNetwork_RoundTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PeerID
		if args[1] != nil {
			arg1 = args[1].(PeerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerNetwork_RoundTrip_Call) Return(peerStream PeerStream, err error) *MockPeerNetwork_RoundTrip_Call {
	_c.Call.Return(peerStream, err)
	return _c
}

func (_c *MockPeerNetwork_RoundTrip_Call) RunAndReturn(run func(context1 context.Context, v PeerID) (PeerStream, error)) *MockPeerNetwork_RoundTrip_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerServerListener creates a new instance of MockPeerServerListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerServerListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerServerListener {
	mock := &MockPeerServerListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerServerListener is an autogenerated mock type for the PeerServerListener type
type MockPeerServerListener struct {
	mock.Mock
}

type MockPeerServerListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerServerListener) EXPECT() *MockPeerServerListener_Expecter {
	return &MockPeerServerListener_Expecter{mock: &_m.Mock}
}

// OnClosePeerConn provides a mock function for the type MockPeerServerListener
func (_mock *MockPeerServerListener) OnClosePeerConn(ctx context.Context, conn PeerConn) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for OnClosePeerConn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerConn) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerServerListener_OnClosePeerConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnClosePeerConn'
type MockPeerServerListener_OnClosePeerConn_Call struct {
	*mock.Call
}

// OnClosePeerConn is a helper method to define mock.On call
//   - ctx context.Context
//   - conn PeerConn
func (_e *MockPeerServerListener_Expecter) OnClosePeerConn(ctx any, conn any) *MockPeerServerListener_OnClosePeerConn_Call {
	return &MockPeerServerListener_OnClosePeerConn_Call{Call: _e.mock.On("OnClosePeerConn", ctx, conn)}
}

func (_c *MockPeerServerListener_OnClosePeerConn_Call) Run(run func(ctx context.Context, conn PeerConn)) *MockPeerServerListener_OnClosePeerConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PeerConn
		if args[1] != nil {
			arg1 = args[1].(PeerConn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerServerListener_OnClosePeerConn_Call) Return(err error) *MockPeerServerListener_OnClosePeerConn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerServerListener_OnClosePeerConn_Call) RunAndReturn(run func(ctx context.Context, conn PeerConn) error) *MockPeerServerListener_OnClosePeerConn_Call {
	_c.Call.Return(run)
	return _c
}

// OnServePeerConn provides a mock function for the type MockPeerServerListener
func (_mock *MockPeerServerListener) OnServePeerConn(ctx context.Context, conn PeerConn) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for OnServePeerConn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerConn) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerServerListener_OnServePeerConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnServePeerConn'
type MockPeerServerListener_OnServePeerConn_Call struct {
	*mock.Call
}

// OnServePeerConn is a helper method to define mock.On call
//   - ctx context.Context
//   - conn PeerConn
func (_e *MockPeerServerListener_Expecter) OnServePeerConn(ctx any, conn any) *MockPeerServerListener_OnServePeerConn_Call {
	return &MockPeerServerListener_OnServePeerConn_Call{Call: _e.mock.On("OnServePeerConn", ctx, conn)}
}

func (_c *MockPeerServerListener_OnServePeerConn_Call) Run(run func(ctx context.Context, conn PeerConn)) *MockPeerServerListener_OnServePeerConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PeerConn
		if args[1] != nil {
			arg1 = args[1].(PeerConn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerServerListener_OnServePeerConn_Call) Return(err error) *MockPeerServerListener_OnServePeerConn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerServerListener_OnServePeerConn_Call) RunAndReturn(run func(ctx context.Context, conn PeerConn) error) *MockPeerServerListener_OnServePeerConn_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerServer creates a new instance of MockPeerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerServer {
	mock := &MockPeerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerServer is an autogenerated mock type for the PeerServer type
type MockPeerServer struct {
	mock.Mock
}

type MockPeerServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerServer) EXPECT() *MockPeerServer_Expecter {
	return &MockPeerServer_Expecter{mock: &_m.Mock}
}

// Serve provides a mock function for the type MockPeerServer
func (_mock *MockPeerServer) Serve(ctx context.Context, conn PeerConn) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PeerConn) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeerServer_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockPeerServer_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - ctx context.Context
//   - conn PeerConn
func (_e *MockPeerServer_Expecter) Serve(ctx any, conn any) *MockPeerServer_Serve_Call {
	return &MockPeerServer_Serve_Call{Call: _e.mock.On("Serve", ctx, conn)}
}

func (_c *MockPeerServer_Serve_Call) Run(run func(ctx context.Context, conn PeerConn)) *MockPeerServer_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PeerConn
		if args[1] != nil {
			arg1 = args[1].(PeerConn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeerServer_Serve_Call) Return(err error) *MockPeerServer_Serve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeerServer_Serve_Call) RunAndReturn(run func(ctx context.Context, conn PeerConn) error) *MockPeerServer_Serve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeerServletRouter creates a new instance of MockPeerServletRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerServletRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerServletRouter {
	mock := &MockPeerServletRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerServletRouter is an autogenerated mock type for the PeerServletRouter type
type MockPeerServletRouter struct {
	mock.Mock
}

type MockPeerServletRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerServletRouter) EXPECT() *MockPeerServletRouter_Expecter {
	return &MockPeerServletRouter_Expecter{mock: &_m.Mock}
}

// Default provides a mock function for the type MockPeerServletRouter
func (_mock *MockPeerServletRouter) Default(handleFuncs ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext] {
	// servlet.HandleFunc[PeerServletContext]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Default")
	}

	var r0 servlet.HandleGroup[PeerServletContext]
	if returnFunc, ok := ret.Get(0).(func(...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext]); ok {
		r0 = returnFunc(handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[PeerServletContext])
		}
	}
	return r0
}

// MockPeerServletRouter_Default_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Default'
type MockPeerServletRouter_Default_Call struct {
	*mock.Call
}

// Default is a helper method to define mock.On call
//   - handleFuncs ...servlet.HandleFunc[PeerServletContext]
func (_e *MockPeerServletRouter_Expecter) Default(handleFuncs ...any) *MockPeerServletRouter_Default_Call {
	return &MockPeerServletRouter_Default_Call{Call: _e.mock.On("Default",
		append([]any{}, handleFuncs...)...)}
}

func (_c *MockPeerServletRouter_Default_Call) Run(run func(handleFuncs ...servlet.HandleFunc[PeerServletContext])) *MockPeerServletRouter_Default_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []servlet.HandleFunc[PeerServletContext]
		variadicArgs := make([]servlet.HandleFunc[PeerServletContext], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(servlet.HandleFunc[PeerServletContext])
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockPeerServletRouter_Default_Call) Return(handleGroup servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Default_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockPeerServletRouter_Default_Call) RunAndReturn(run func(handleFuncs ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Default_Call {
	_c.Call.Return(run)
	return _c
}

// Group provides a mock function for the type MockPeerServletRouter
func (_mock *MockPeerServletRouter) Group() servlet.HandleGroup[PeerServletContext] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 servlet.HandleGroup[PeerServletContext]
	if returnFunc, ok := ret.Get(0).(func() servlet.HandleGroup[PeerServletContext]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[PeerServletContext])
		}
	}
	return r0
}

// MockPeerServletRouter_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockPeerServletRouter_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
func (_e *MockPeerServletRouter_Expecter) Group() *MockPeerServletRouter_Group_Call {
	return &MockPeerServletRouter_Group_Call{Call: _e.mock.On("Group")}
}

func (_c *MockPeerServletRouter_Group_Call) Run(run func()) *MockPeerServletRouter_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerServletRouter_Group_Call) Return(handleGroup servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Group_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockPeerServletRouter_Group_Call) RunAndReturn(run func() servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Group_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type MockPeerServletRouter
func (_mock *MockPeerServletRouter) Handle(v servlet.RequestName, handleFuncs ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext] {
	// servlet.HandleFunc[PeerServletContext]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, v)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 servlet.HandleGroup[PeerServletContext]
	if returnFunc, ok := ret.Get(0).(func(servlet.RequestName, ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext]); ok {
		r0 = returnFunc(v, handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[PeerServletContext])
		}
	}
	return r0
}

// MockPeerServletRouter_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockPeerServletRouter_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - v servlet.RequestName
//   - handleFuncs ...servlet.HandleFunc[PeerServletContext]
func (_e *MockPeerServletRouter_Expecter) Handle(v any, handleFuncs ...any) *MockPeerServletRouter_Handle_Call {
	return &MockPeerServletRouter_Handle_Call{Call: _e.mock.On("Handle",
		append([]any{v}, handleFuncs...)...)}
}

func (_c *MockPeerServletRouter_Handle_Call) Run(run func(v servlet.RequestName, handleFuncs ...servlet.HandleFunc[PeerServletContext])) *MockPeerServletRouter_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 servlet.RequestName
		if args[0] != nil {
			arg0 = args[0].(servlet.RequestName)
		}
		var arg1 []servlet.HandleFunc[PeerServletContext]
		variadicArgs := make([]servlet.HandleFunc[PeerServletContext], len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(servlet.HandleFunc[PeerServletContext])
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockPeerServletRouter_Handle_Call) Return(handleGroup servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Handle_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockPeerServletRouter_Handle_Call) RunAndReturn(run func(v servlet.RequestName, handleFuncs ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Route provides a mock function for the type MockPeerServletRouter
func (_mock *MockPeerServletRouter) Route(v servlet.RequestName) servlet.HandleGroup[PeerServletContext] {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 servlet.HandleGroup[PeerServletContext]
	if returnFunc, ok := ret.Get(0).(func(servlet.RequestName) servlet.HandleGroup[PeerServletContext]); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[PeerServletContext])
		}
	}
	return r0
}

// MockPeerServletRouter_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockPeerServletRouter_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - v servlet.RequestName
func (_e *MockPeerServletRouter_Expecter) Route(v any) *MockPeerServletRouter_Route_Call {
	return &MockPeerServletRouter_Route_Call{Call: _e.mock.On("Route", v)}
}

func (_c *MockPeerServletRouter_Route_Call) Run(run func(v servlet.RequestName)) *MockPeerServletRouter_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 servlet.RequestName
		if args[0] != nil {
			arg0 = args[0].(servlet.RequestName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerServletRouter_Route_Call) Return(handleGroup servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Route_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockPeerServletRouter_Route_Call) RunAndReturn(run func(v servlet.RequestName) servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Route_Call {
	_c.Call.Return(run)
	return _c
}

// Use provides a mock function for the type MockPeerServletRouter
func (_mock *MockPeerServletRouter) Use(handleFuncs ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext] {
	// servlet.HandleFunc[PeerServletContext]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Use")
	}

	var r0 servlet.HandleGroup[PeerServletContext]
	if returnFunc, ok := ret.Get(0).(func(...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext]); ok {
		r0 = returnFunc(handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[PeerServletContext])
		}
	}
	return r0
}

// MockPeerServletRouter_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockPeerServletRouter_Use_Call struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - handleFuncs ...servlet.HandleFunc[PeerServletContext]
func (_e *MockPeerServletRouter_Expecter) Use(handleFuncs ...any) *MockPeerServletRouter_Use_Call {
	return &MockPeerServletRouter_Use_Call{Call: _e.mock.On("Use",
		append([]any{}, handleFuncs...)...)}
}

func (_c *MockPeerServletRouter_Use_Call) Run(run func(handleFuncs ...servlet.HandleFunc[PeerServletContext])) *MockPeerServletRouter_Use_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []servlet.HandleFunc[PeerServletContext]
		variadicArgs := make([]servlet.HandleFunc[PeerServletContext], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(servlet.HandleFunc[PeerServletContext])
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockPeerServletRouter_Use_Call) Return(handleGroup servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Use_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockPeerServletRouter_Use_Call) RunAndReturn(run func(handleFuncs ...servlet.HandleFunc[PeerServletContext]) servlet.HandleGroup[PeerServletContext]) *MockPeerServletRouter_Use_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuicConfig creates a new instance of MockQuicConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuicConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuicConfig {
	mock := &MockQuicConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuicConfig is an autogenerated mock type for the QuicConfig type
type MockQuicConfig struct {
	mock.Mock
}

type MockQuicConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuicConfig) EXPECT() *MockQuicConfig_Expecter {
	return &MockQuicConfig_Expecter{mock: &_m.Mock}
}

// Addrs provides a mock function for the type MockQuicConfig
func (_mock *MockQuicConfig) Addrs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addrs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockQuicConfig_Addrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addrs'
type MockQuicConfig_Addrs_Call struct {
	*mock.Call
}

// Addrs is a helper method to define mock.On call
func (_e *MockQuicConfig_Expecter) Addrs() *MockQuicConfig_Addrs_Call {
	return &MockQuicConfig_Addrs_Call{Call: _e.mock.On("Addrs")}
}

func (_c *MockQuicConfig_Addrs_Call) Run(run func()) *MockQuicConfig_Addrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfig_Addrs_Call) Return(strings []string) *MockQuicConfig_Addrs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockQuicConfig_Addrs_Call) RunAndReturn(run func() []string) *MockQuicConfig_Addrs_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastEnabled provides a mock function for the type MockQuicConfig
func (_mock *MockQuicConfig) BroadcastEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockQuicConfig_BroadcastEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastEnabled'
type MockQuicConfig_BroadcastEnabled_Call struct {
	*mock.Call
}

// BroadcastEnabled is a helper method to define mock.On call
func (_e *MockQuicConfig_Expecter) BroadcastEnabled() *MockQuicConfig_BroadcastEnabled_Call {
	return &MockQuicConfig_BroadcastEnabled_Call{Call: _e.mock.On("BroadcastEnabled")}
}

func (_c *MockQuicConfig_BroadcastEnabled_Call) Run(run func()) *MockQuicConfig_BroadcastEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfig_BroadcastEnabled_Call) Return(b bool) *MockQuicConfig_BroadcastEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockQuicConfig_BroadcastEnabled_Call) RunAndReturn(run func() bool) *MockQuicConfig_BroadcastEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Certificate provides a mock function for the type MockQuicConfig
func (_mock *MockQuicConfig) Certificate() tls.Certificate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Certificate")
	}

	var r0 tls.Certificate
	if returnFunc, ok := ret.Get(0).(func() tls.Certificate); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(tls.Certificate)
	}
	return r0
}

// MockQuicConfig_Certificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Certificate'
type MockQuicConfig_Certificate_Call struct {
	*mock.Call
}

// Certificate is a helper method to define mock.On call
func (_e *MockQuicConfig_Expecter) Certificate() *MockQuicConfig_Certificate_Call {
	return &MockQuicConfig_Certificate_Call{Call: _e.mock.On("Certificate")}
}

func (_c *MockQuicConfig_Certificate_Call) Run(run func()) *MockQuicConfig_Certificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfig_Certificate_Call) Return(certificate tls.Certificate) *MockQuicConfig_Certificate_Call {
	_c.Call.Return(certificate)
	return _c
}

func (_c *MockQuicConfig_Certificate_Call) RunAndReturn(run func() tls.Certificate) *MockQuicConfig_Certificate_Call {
	_c.Call.Return(run)
	return _c
}

// PeerID provides a mock function for the type MockQuicConfig
func (_mock *MockQuicConfig) PeerID() PeerID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PeerID")
	}

	var r0 PeerID
	if returnFunc, ok := ret.Get(0).(func() PeerID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PeerID)
		}
	}
	return r0
}

// MockQuicConfig_PeerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerID'
type MockQuicConfig_PeerID_Call struct {
	*mock.Call
}

// PeerID is a helper method to define mock.On call
func (_e *MockQuicConfig_Expecter) PeerID() *MockQuicConfig_PeerID_Call {
	return &MockQuicConfig_PeerID_Call{Call: _e.mock.On("PeerID")}
}

func (_c *MockQuicConfig_PeerID_Call) Run(run func()) *MockQuicConfig_PeerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfig_PeerID_Call) Return(v PeerID) *MockQuicConfig_PeerID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockQuicConfig_PeerID_Call) RunAndReturn(run func() PeerID) *MockQuicConfig_PeerID_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function for the type MockQuicConfig
func (_mock *MockQuicConfig) Port() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockQuicConfig_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type MockQuicConfig_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *MockQuicConfig_Expecter) Port() *MockQuicConfig_Port_Call {
	return &MockQuicConfig_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *MockQuicConfig_Port_Call) Run(run func()) *MockQuicConfig_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfig_Port_Call) Return(v uint16) *MockQuicConfig_Port_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockQuicConfig_Port_Call) RunAndReturn(run func() uint16) *MockQuicConfig_Port_Call {
	_c.Call.Return(run)
	return _c
}

// PrivateKey provides a mock function for the type MockQuicConfig
func (_mock *MockQuicConfig) PrivateKey() crypto.PrivateKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrivateKey")
	}

	var r0 crypto.PrivateKey
	if returnFunc, ok := ret.Get(0).(func() crypto.PrivateKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivateKey)
		}
	}
	return r0
}

// MockQuicConfig_PrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrivateKey'
type MockQuicConfig_PrivateKey_Call struct {
	*mock.Call
}

// PrivateKey is a helper method to define mock.On call
func (_e *MockQuicConfig_Expecter) PrivateKey() *MockQuicConfig_PrivateKey_Call {
	return &MockQuicConfig_PrivateKey_Call{Call: _e.mock.On("PrivateKey")}
}

func (_c *MockQuicConfig_PrivateKey_Call) Run(run func()) *MockQuicConfig_PrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfig_PrivateKey_Call) Return(privateKey crypto.PrivateKey) *MockQuicConfig_PrivateKey_Call {
	_c.Call.Return(privateKey)
	return _c
}

func (_c *MockQuicConfig_PrivateKey_Call) RunAndReturn(run func() crypto.PrivateKey) *MockQuicConfig_PrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuicConfigListener creates a new instance of MockQuicConfigListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuicConfigListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuicConfigListener {
	mock := &MockQuicConfigListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuicConfigListener is an autogenerated mock type for the QuicConfigListener type
type MockQuicConfigListener struct {
	mock.Mock
}

type MockQuicConfigListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuicConfigListener) EXPECT() *MockQuicConfigListener_Expecter {
	return &MockQuicConfigListener_Expecter{mock: &_m.Mock}
}

// OnConfigUpdated provides a mock function for the type MockQuicConfigListener
func (_mock *MockQuicConfigListener) OnConfigUpdated(config1 QuicConfig) {
	_mock.Called(config1)
	return
}

// MockQuicConfigListener_OnConfigUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigUpdated'
type MockQuicConfigListener_OnConfigUpdated_Call struct {
	*mock.Call
}

// OnConfigUpdated is a helper method to define mock.On call
//   - config1 QuicConfig
func (_e *MockQuicConfigListener_Expecter) OnConfigUpdated(config1 any) *MockQuicConfigListener_OnConfigUpdated_Call {
	return &MockQuicConfigListener_OnConfigUpdated_Call{Call: _e.mock.On("OnConfigUpdated", config1)}
}

func (_c *MockQuicConfigListener_OnConfigUpdated_Call) Run(run func(config1 QuicConfig)) *MockQuicConfigListener_OnConfigUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 QuicConfig
		if args[0] != nil {
			arg0 = args[0].(QuicConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuicConfigListener_OnConfigUpdated_Call) Return() *MockQuicConfigListener_OnConfigUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuicConfigListener_OnConfigUpdated_Call) RunAndReturn(run func(config1 QuicConfig)) *MockQuicConfigListener_OnConfigUpdated_Call {
	_c.Run(run)
	return _c
}

// NewMockQuicConfigurer creates a new instance of MockQuicConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuicConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuicConfigurer {
	mock := &MockQuicConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuicConfigurer is an autogenerated mock type for the QuicConfigurer type
type MockQuicConfigurer struct {
	mock.Mock
}

type MockQuicConfigurer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuicConfigurer) EXPECT() *MockQuicConfigurer_Expecter {
	return &MockQuicConfigurer_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockQuicConfigurer
func (_mock *MockQuicConfigurer) Config() QuicConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 QuicConfig
	if returnFunc, ok := ret.Get(0).(func() QuicConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(QuicConfig)
		}
	}
	return r0
}

// MockQuicConfigurer_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockQuicConfigurer_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockQuicConfigurer_Expecter) Config() *MockQuicConfigurer_Config_Call {
	return &MockQuicConfigurer_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockQuicConfigurer_Config_Call) Run(run func()) *MockQuicConfigurer_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfigurer_Config_Call) Return(quicConfig QuicConfig) *MockQuicConfigurer_Config_Call {
	_c.Call.Return(quicConfig)
	return _c
}

func (_c *MockQuicConfigurer_Config_Call) RunAndReturn(run func() QuicConfig) *MockQuicConfigurer_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigListeners provides a mock function for the type MockQuicConfigurer
func (_mock *MockQuicConfigurer) ConfigListeners() []config.ConfigurerListener[QuicConfig] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigListeners")
	}

	var r0 []config.ConfigurerListener[QuicConfig]
	if returnFunc, ok := ret.Get(0).(func() []config.ConfigurerListener[QuicConfig]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ConfigurerListener[QuicConfig])
		}
	}
	return r0
}

// MockQuicConfigurer_ConfigListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigListeners'
type MockQuicConfigurer_ConfigListeners_Call struct {
	*mock.Call
}

// ConfigListeners is a helper method to define mock.On call
func (_e *MockQuicConfigurer_Expecter) ConfigListeners() *MockQuicConfigurer_ConfigListeners_Call {
	return &MockQuicConfigurer_ConfigListeners_Call{Call: _e.mock.On("ConfigListeners")}
}

func (_c *MockQuicConfigurer_ConfigListeners_Call) Run(run func()) *MockQuicConfigurer_ConfigListeners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQuicConfigurer_ConfigListeners_Call) Return(configurerListeners []config.ConfigurerListener[QuicConfig]) *MockQuicConfigurer_ConfigListeners_Call {
	_c.Call.Return(configurerListeners)
	return _c
}

func (_c *MockQuicConfigurer_ConfigListeners_Call) RunAndReturn(run func() []config.ConfigurerListener[QuicConfig]) *MockQuicConfigurer_ConfigListeners_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type MockQuicConfigurer
func (_mock *MockQuicConfigurer) Configure(config1 QuicConfig) error {
	ret := _mock.Called(config1)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(QuicConfig) error); ok {
		r0 = returnFunc(config1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuicConfigurer_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockQuicConfigurer_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - config1 QuicConfig
func (_e *MockQuicConfigurer_Expecter) Configure(config1 any) *MockQuicConfigurer_Configure_Call {
	return &MockQuicConfigurer_Configure_Call{Call: _e.mock.On("Configure", config1)}
}

func (_c *MockQuicConfigurer_Configure_Call) Run(run func(config1 QuicConfig)) *MockQuicConfigurer_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 QuicConfig
		if args[0] != nil {
			arg0 = args[0].(QuicConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuicConfigurer_Configure_Call) Return(err error) *MockQuicConfigurer_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuicConfigurer_Configure_Call) RunAndReturn(run func(config1 QuicConfig) error) *MockQuicConfigurer_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockQuicConfigurer
func (_mock *MockQuicConfigurer) Subscribe(listener config.ConfigurerListener[QuicConfig]) {
	_mock.Called(listener)
	return
}

// MockQuicConfigurer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockQuicConfigurer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[QuicConfig]
func (_e *MockQuicConfigurer_Expecter) Subscribe(listener any) *MockQuicConfigurer_Subscribe_Call {
	return &MockQuicConfigurer_Subscribe_Call{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *MockQuicConfigurer_Subscribe_Call) Run(run func(listener config.ConfigurerListener[QuicConfig])) *MockQuicConfigurer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[QuicConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[QuicConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuicConfigurer_Subscribe_Call) Return() *MockQuicConfigurer_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuicConfigurer_Subscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[QuicConfig])) *MockQuicConfigurer_Subscribe_Call {
	_c.Run(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockQuicConfigurer
func (_mock *MockQuicConfigurer) Unsubscribe(listener config.ConfigurerListener[QuicConfig]) {
	_mock.Called(listener)
	return
}

// MockQuicConfigurer_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockQuicConfigurer_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[QuicConfig]
func (_e *MockQuicConfigurer_Expecter) Unsubscribe(listener any) *MockQuicConfigurer_Unsubscribe_Call {
	return &MockQuicConfigurer_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", listener)}
}

func (_c *MockQuicConfigurer_Unsubscribe_Call) Run(run func(listener config.ConfigurerListener[QuicConfig])) *MockQuicConfigurer_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[QuicConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[QuicConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuicConfigurer_Unsubscribe_Call) Return() *MockQuicConfigurer_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQuicConfigurer_Unsubscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[QuicConfig])) *MockQuicConfigurer_Unsubscribe_Call {
	_c.Run(run)
	return _c
}

// NewMockQuicGuide creates a new instance of MockQuicGuide. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuicGuide(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuicGuide {
	mock := &MockQuicGuide{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuicGuide is an autogenerated mock type for the QuicGuide type
type MockQuicGuide struct {
	mock.Mock
}

type MockQuicGuide_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuicGuide) EXPECT() *MockQuicGuide_Expecter {
	return &MockQuicGuide_Expecter{mock: &_m.Mock}
}

// LookupQuicAddr provides a mock function for the type MockQuicGuide
func (_mock *MockQuicGuide) LookupQuicAddr(peerId PeerID) (iter.Seq[string], error) {
	ret := _mock.Called(peerId)

	if len(ret) == 0 {
		panic("no return value specified for LookupQuicAddr")
	}

	var r0 iter.Seq[string]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(PeerID) (iter.Seq[string], error)); ok {
		return returnFunc(peerId)
	}
	if returnFunc, ok := ret.Get(0).(func(PeerID) iter.Seq[string]); ok {
		r0 = returnFunc(peerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[string])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(PeerID) error); ok {
		r1 = returnFunc(peerId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuicGuide_LookupQuicAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupQuicAddr'
type MockQuicGuide_LookupQuicAddr_Call struct {
	*mock.Call
}

// LookupQuicAddr is a helper method to define mock.On call
//   - peerId PeerID
func (_e *MockQuicGuide_Expecter) LookupQuicAddr(peerId any) *MockQuicGuide_LookupQuicAddr_Call {
	return &MockQuicGuide_LookupQuicAddr_Call{Call: _e.mock.On("LookupQuicAddr", peerId)}
}

func (_c *MockQuicGuide_LookupQuicAddr_Call) Run(run func(peerId PeerID)) *MockQuicGuide_LookupQuicAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PeerID
		if args[0] != nil {
			arg0 = args[0].(PeerID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuicGuide_LookupQuicAddr_Call) Return(seq iter.Seq[string], err error) *MockQuicGuide_LookupQuicAddr_Call {
	_c.Call.Return(seq, err)
	return _c
}

func (_c *MockQuicGuide_LookupQuicAddr_Call) RunAndReturn(run func(peerId PeerID) (iter.Seq[string], error)) *MockQuicGuide_LookupQuicAddr_Call {
	_c.Call.Return(run)
	return _c
}
