// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.9
// source: extfs/proto/remote_search_file.proto

package remotesearchfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteSearchFileRecordList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*RemoteSearchFileRecord `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	Total   int64                     `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Hash    string                    `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *RemoteSearchFileRecordList) Reset() {
	*x = RemoteSearchFileRecordList{}
	mi := &file_extfs_proto_remote_search_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteSearchFileRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSearchFileRecordList) ProtoMessage() {}

func (x *RemoteSearchFileRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_search_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSearchFileRecordList.ProtoReflect.Descriptor instead.
func (*RemoteSearchFileRecordList) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_search_file_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteSearchFileRecordList) GetRecords() []*RemoteSearchFileRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RemoteSearchFileRecordList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RemoteSearchFileRecordList) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type RemoteSearchFileRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ItemID    uint32   `protobuf:"varint,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	Name      string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	FilePath  string   `protobuf:"bytes,4,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	FileType  string   `protobuf:"bytes,5,opt,name=FileType,proto3" json:"FileType,omitempty"`
	MimeType  string   `protobuf:"bytes,6,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	Tokens    []string `protobuf:"bytes,7,rep,name=Tokens,proto3" json:"Tokens,omitempty"`
	Score     uint32   `protobuf:"varint,8,opt,name=Score,proto3" json:"Score,omitempty"`
	Size      int64    `protobuf:"varint,9,opt,name=Size,proto3" json:"Size,omitempty"`
	Available bool     `protobuf:"varint,10,opt,name=Available,proto3" json:"Available,omitempty"`
	CreatedAt int64    `protobuf:"varint,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt int64    `protobuf:"varint,12,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *RemoteSearchFileRecord) Reset() {
	*x = RemoteSearchFileRecord{}
	mi := &file_extfs_proto_remote_search_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteSearchFileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSearchFileRecord) ProtoMessage() {}

func (x *RemoteSearchFileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_search_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSearchFileRecord.ProtoReflect.Descriptor instead.
func (*RemoteSearchFileRecord) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_search_file_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteSearchFileRecord) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RemoteSearchFileRecord) GetItemID() uint32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *RemoteSearchFileRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteSearchFileRecord) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RemoteSearchFileRecord) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *RemoteSearchFileRecord) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RemoteSearchFileRecord) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RemoteSearchFileRecord) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RemoteSearchFileRecord) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RemoteSearchFileRecord) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *RemoteSearchFileRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RemoteSearchFileRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type RemoteSearchFileRecordSearchCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RangeStart int32  `protobuf:"varint,1,opt,name=RangeStart,proto3" json:"RangeStart,omitempty"`
	RangeEnd   int32  `protobuf:"varint,2,opt,name=RangeEnd,proto3" json:"RangeEnd,omitempty"`
	Query      string `protobuf:"bytes,3,opt,name=Query,proto3" json:"Query,omitempty"`
	Hash       string `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *RemoteSearchFileRecordSearchCondition) Reset() {
	*x = RemoteSearchFileRecordSearchCondition{}
	mi := &file_extfs_proto_remote_search_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteSearchFileRecordSearchCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSearchFileRecordSearchCondition) ProtoMessage() {}

func (x *RemoteSearchFileRecordSearchCondition) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_search_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSearchFileRecordSearchCondition.ProtoReflect.Descriptor instead.
func (*RemoteSearchFileRecordSearchCondition) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_search_file_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteSearchFileRecordSearchCondition) GetRangeStart() int32 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *RemoteSearchFileRecordSearchCondition) GetRangeEnd() int32 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

func (x *RemoteSearchFileRecordSearchCondition) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RemoteSearchFileRecordSearchCondition) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_extfs_proto_remote_search_file_proto protoreflect.FileDescriptor

var file_extfs_proto_remote_search_file_proto_rawDesc = []byte{
	0x0a, 0x24, 0x65, 0x78, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0xc4, 0x02, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x8d, 0x01, 0x0a,
	0x25, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x42, 0x2b, 0x5a, 0x29,
	0x65, 0x78, 0x74, 0x66, 0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x3b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_extfs_proto_remote_search_file_proto_rawDescOnce sync.Once
	file_extfs_proto_remote_search_file_proto_rawDescData = file_extfs_proto_remote_search_file_proto_rawDesc
)

func file_extfs_proto_remote_search_file_proto_rawDescGZIP() []byte {
	file_extfs_proto_remote_search_file_proto_rawDescOnce.Do(func() {
		file_extfs_proto_remote_search_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_extfs_proto_remote_search_file_proto_rawDescData)
	})
	return file_extfs_proto_remote_search_file_proto_rawDescData
}

var file_extfs_proto_remote_search_file_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_extfs_proto_remote_search_file_proto_goTypes = []any{
	(*RemoteSearchFileRecordList)(nil),            // 0: remotesearchfile.RemoteSearchFileRecordList
	(*RemoteSearchFileRecord)(nil),                // 1: remotesearchfile.RemoteSearchFileRecord
	(*RemoteSearchFileRecordSearchCondition)(nil), // 2: remotesearchfile.RemoteSearchFileRecordSearchCondition
}
var file_extfs_proto_remote_search_file_proto_depIdxs = []int32{
	1, // 0: remotesearchfile.RemoteSearchFileRecordList.Records:type_name -> remotesearchfile.RemoteSearchFileRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extfs_proto_remote_search_file_proto_init() }
func file_extfs_proto_remote_search_file_proto_init() {
	if File_extfs_proto_remote_search_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extfs_proto_remote_search_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extfs_proto_remote_search_file_proto_goTypes,
		DependencyIndexes: file_extfs_proto_remote_search_file_proto_depIdxs,
		MessageInfos:      file_extfs_proto_remote_search_file_proto_msgTypes,
	}.Build()
	File_extfs_proto_remote_search_file_proto = out.File
	file_extfs_proto_remote_search_file_proto_rawDesc = nil
	file_extfs_proto_remote_search_file_proto_goTypes = nil
	file_extfs_proto_remote_search_file_proto_depIdxs = nil
}
