syntax = "proto3";
package remoteitem;

option go_package = "extfs/remote_item;remoteitem";

message RemoteFileInfoRecordList {
    repeated RemoteFileInfoRecord Items = 1;
}

message RemoteFileInfoRecord {
    string ID = 1;
    int64 CreatedAt = 2;
    int64 UpdatedAt = 3;
    uint32 ItemID = 4;
    string Name = 5;
    string FileType = 6;
    string FilePath = 7;
    string ParentPath = 8;
    int64 Size = 9;
    bool Available = 10;
}

message RemoteFileInfoRecordSearchCondition {
    uint32 ItemID = 1;
    string ParentPath = 2;
}

message RemoteFileInfoRecordSelectCondition {
    uint32 ItemID = 1;
    string FilePath = 2;
}
