// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servlet

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandleContext creates a new instance of MockHandleContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandleContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandleContext {
	mock := &MockHandleContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandleContext is an autogenerated mock type for the HandleContext type
type MockHandleContext struct {
	mock.Mock
}

type MockHandleContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandleContext) EXPECT() *MockHandleContext_Expecter {
	return &MockHandleContext_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockHandleContext
func (_mock *MockHandleContext) Name() RequestName {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 RequestName
	if returnFunc, ok := ret.Get(0).(func() RequestName); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(RequestName)
		}
	}
	return r0
}

// MockHandleContext_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHandleContext_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHandleContext_Expecter) Name() *MockHandleContext_Name_Call {
	return &MockHandleContext_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHandleContext_Name_Call) Run(run func()) *MockHandleContext_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandleContext_Name_Call) Return(v RequestName) *MockHandleContext_Name_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockHandleContext_Name_Call) RunAndReturn(run func() RequestName) *MockHandleContext_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandleGroup creates a new instance of MockHandleGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandleGroup[T HandleContext](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandleGroup[T] {
	mock := &MockHandleGroup[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandleGroup is an autogenerated mock type for the HandleGroup type
type MockHandleGroup[T HandleContext] struct {
	mock.Mock
}

type MockHandleGroup_Expecter[T HandleContext] struct {
	mock *mock.Mock
}

func (_m *MockHandleGroup[T]) EXPECT() *MockHandleGroup_Expecter[T] {
	return &MockHandleGroup_Expecter[T]{mock: &_m.Mock}
}

// Default provides a mock function for the type MockHandleGroup
func (_mock *MockHandleGroup[T]) Default(handleFuncs ...HandleFunc[T]) HandleGroup[T] {
	// HandleFunc[T]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Default")
	}

	var r0 HandleGroup[T]
	if returnFunc, ok := ret.Get(0).(func(...HandleFunc[T]) HandleGroup[T]); ok {
		r0 = returnFunc(handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(HandleGroup[T])
		}
	}
	return r0
}

// MockHandleGroup_Default_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Default'
type MockHandleGroup_Default_Call[T HandleContext] struct {
	*mock.Call
}

// Default is a helper method to define mock.On call
//   - handleFuncs ...HandleFunc[T]
func (_e *MockHandleGroup_Expecter[T]) Default(handleFuncs ...any) *MockHandleGroup_Default_Call[T] {
	return &MockHandleGroup_Default_Call[T]{Call: _e.mock.On("Default",
		append([]any{}, handleFuncs...)...)}
}

func (_c *MockHandleGroup_Default_Call[T]) Run(run func(handleFuncs ...HandleFunc[T])) *MockHandleGroup_Default_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []HandleFunc[T]
		variadicArgs := make([]HandleFunc[T], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(HandleFunc[T])
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockHandleGroup_Default_Call[T]) Return(handleGroup HandleGroup[T]) *MockHandleGroup_Default_Call[T] {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockHandleGroup_Default_Call[T]) RunAndReturn(run func(handleFuncs ...HandleFunc[T]) HandleGroup[T]) *MockHandleGroup_Default_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Group provides a mock function for the type MockHandleGroup
func (_mock *MockHandleGroup[T]) Group() HandleGroup[T] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 HandleGroup[T]
	if returnFunc, ok := ret.Get(0).(func() HandleGroup[T]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(HandleGroup[T])
		}
	}
	return r0
}

// MockHandleGroup_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockHandleGroup_Group_Call[T HandleContext] struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
func (_e *MockHandleGroup_Expecter[T]) Group() *MockHandleGroup_Group_Call[T] {
	return &MockHandleGroup_Group_Call[T]{Call: _e.mock.On("Group")}
}

func (_c *MockHandleGroup_Group_Call[T]) Run(run func()) *MockHandleGroup_Group_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandleGroup_Group_Call[T]) Return(handleGroup HandleGroup[T]) *MockHandleGroup_Group_Call[T] {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockHandleGroup_Group_Call[T]) RunAndReturn(run func() HandleGroup[T]) *MockHandleGroup_Group_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type MockHandleGroup
func (_mock *MockHandleGroup[T]) Handle(v RequestName, handleFuncs ...HandleFunc[T]) HandleGroup[T] {
	// HandleFunc[T]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, v)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 HandleGroup[T]
	if returnFunc, ok := ret.Get(0).(func(RequestName, ...HandleFunc[T]) HandleGroup[T]); ok {
		r0 = returnFunc(v, handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(HandleGroup[T])
		}
	}
	return r0
}

// MockHandleGroup_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHandleGroup_Handle_Call[T HandleContext] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - v RequestName
//   - handleFuncs ...HandleFunc[T]
func (_e *MockHandleGroup_Expecter[T]) Handle(v any, handleFuncs ...any) *MockHandleGroup_Handle_Call[T] {
	return &MockHandleGroup_Handle_Call[T]{Call: _e.mock.On("Handle",
		append([]any{v}, handleFuncs...)...)}
}

func (_c *MockHandleGroup_Handle_Call[T]) Run(run func(v RequestName, handleFuncs ...HandleFunc[T])) *MockHandleGroup_Handle_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RequestName
		if args[0] != nil {
			arg0 = args[0].(RequestName)
		}
		var arg1 []HandleFunc[T]
		variadicArgs := make([]HandleFunc[T], len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(HandleFunc[T])
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockHandleGroup_Handle_Call[T]) Return(handleGroup HandleGroup[T]) *MockHandleGroup_Handle_Call[T] {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockHandleGroup_Handle_Call[T]) RunAndReturn(run func(v RequestName, handleFuncs ...HandleFunc[T]) HandleGroup[T]) *MockHandleGroup_Handle_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Route provides a mock function for the type MockHandleGroup
func (_mock *MockHandleGroup[T]) Route(v RequestName) HandleGroup[T] {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 HandleGroup[T]
	if returnFunc, ok := ret.Get(0).(func(RequestName) HandleGroup[T]); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(HandleGroup[T])
		}
	}
	return r0
}

// MockHandleGroup_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockHandleGroup_Route_Call[T HandleContext] struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - v RequestName
func (_e *MockHandleGroup_Expecter[T]) Route(v any) *MockHandleGroup_Route_Call[T] {
	return &MockHandleGroup_Route_Call[T]{Call: _e.mock.On("Route", v)}
}

func (_c *MockHandleGroup_Route_Call[T]) Run(run func(v RequestName)) *MockHandleGroup_Route_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 RequestName
		if args[0] != nil {
			arg0 = args[0].(RequestName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandleGroup_Route_Call[T]) Return(handleGroup HandleGroup[T]) *MockHandleGroup_Route_Call[T] {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockHandleGroup_Route_Call[T]) RunAndReturn(run func(v RequestName) HandleGroup[T]) *MockHandleGroup_Route_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Use provides a mock function for the type MockHandleGroup
func (_mock *MockHandleGroup[T]) Use(handleFuncs ...HandleFunc[T]) HandleGroup[T] {
	// HandleFunc[T]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Use")
	}

	var r0 HandleGroup[T]
	if returnFunc, ok := ret.Get(0).(func(...HandleFunc[T]) HandleGroup[T]); ok {
		r0 = returnFunc(handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(HandleGroup[T])
		}
	}
	return r0
}

// MockHandleGroup_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockHandleGroup_Use_Call[T HandleContext] struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - handleFuncs ...HandleFunc[T]
func (_e *MockHandleGroup_Expecter[T]) Use(handleFuncs ...any) *MockHandleGroup_Use_Call[T] {
	return &MockHandleGroup_Use_Call[T]{Call: _e.mock.On("Use",
		append([]any{}, handleFuncs...)...)}
}

func (_c *MockHandleGroup_Use_Call[T]) Run(run func(handleFuncs ...HandleFunc[T])) *MockHandleGroup_Use_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []HandleFunc[T]
		variadicArgs := make([]HandleFunc[T], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(HandleFunc[T])
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockHandleGroup_Use_Call[T]) Return(handleGroup HandleGroup[T]) *MockHandleGroup_Use_Call[T] {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockHandleGroup_Use_Call[T]) RunAndReturn(run func(handleFuncs ...HandleFunc[T]) HandleGroup[T]) *MockHandleGroup_Use_Call[T] {
	_c.Call.Return(run)
	return _c
}
