syntax = "proto3";
package remotefile;

option go_package = "extfs/remote_file;remotefile";

message RemoteFileRecordList {
    repeated RemoteFileRecord Items = 1;
}

message RemoteFileRecord {
    string ID = 1;
    int64 CreatedAt = 2;
    int64 UpdatedAt = 3;
    uint32 ItemID = 4;
    string Name = 5;
    string FileType = 6;
    string FilePath = 7;
    string ParentPath = 8;
    string MimeType = 9;
    int64 Size = 10;
    bool Available = 11;
}

message RemoteFileRecordSearchCondition {
    uint32 ItemID = 1;
    optional string ParentPath = 2;
}

message RemoteFileRecordSelectCondition {
    uint32 ItemID = 1;
    string ParentPath = 2;
    string Name = 3;
}