syntax = "proto3";
package remotesearchfile;

option go_package = "extfs/remote_search_file;remotesearchfile";

message RemoteSearchFileRecordList {
    repeated RemoteSearchFileRecord Records = 1;
    int64 Total = 2;
    string Hash = 3;
}

message RemoteSearchFileRecord {
    uint64 ID = 1;
    uint32 ItemID = 2;
    string Name = 3;
    string FilePath = 4;
    string FileType = 5;
    string MimeType = 6;
    repeated string Tokens = 7;
    bytes Score = 8;
    int64 Size = 9;
    bool Available = 10;
    int64 CreatedAt = 11;
    int64 UpdatedAt = 12;
}

message RemoteSearchFileRecordSearchCondition {
    int32 RangeStart = 1;
    int32 RangeEnd = 2;
    string Query = 3;
    string Hash = 4;
}

