// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigurerListener creates a new instance of MockConfigurerListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurerListener[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurerListener[T] {
	mock := &MockConfigurerListener[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigurerListener is an autogenerated mock type for the ConfigurerListener type
type MockConfigurerListener[T any] struct {
	mock.Mock
}

type MockConfigurerListener_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockConfigurerListener[T]) EXPECT() *MockConfigurerListener_Expecter[T] {
	return &MockConfigurerListener_Expecter[T]{mock: &_m.Mock}
}

// OnConfigUpdated provides a mock function for the type MockConfigurerListener
func (_mock *MockConfigurerListener[T]) OnConfigUpdated(config T) {
	_mock.Called(config)
	return
}

// MockConfigurerListener_OnConfigUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigUpdated'
type MockConfigurerListener_OnConfigUpdated_Call[T any] struct {
	*mock.Call
}

// OnConfigUpdated is a helper method to define mock.On call
//   - config T
func (_e *MockConfigurerListener_Expecter[T]) OnConfigUpdated(config any) *MockConfigurerListener_OnConfigUpdated_Call[T] {
	return &MockConfigurerListener_OnConfigUpdated_Call[T]{Call: _e.mock.On("OnConfigUpdated", config)}
}

func (_c *MockConfigurerListener_OnConfigUpdated_Call[T]) Run(run func(config T)) *MockConfigurerListener_OnConfigUpdated_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurerListener_OnConfigUpdated_Call[T]) Return() *MockConfigurerListener_OnConfigUpdated_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurerListener_OnConfigUpdated_Call[T]) RunAndReturn(run func(config T)) *MockConfigurerListener_OnConfigUpdated_Call[T] {
	_c.Run(run)
	return _c
}

// NewMockConfigurer creates a new instance of MockConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurer[T] {
	mock := &MockConfigurer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigurer is an autogenerated mock type for the Configurer type
type MockConfigurer[T any] struct {
	mock.Mock
}

type MockConfigurer_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockConfigurer[T]) EXPECT() *MockConfigurer_Expecter[T] {
	return &MockConfigurer_Expecter[T]{mock: &_m.Mock}
}

// Config provides a mock function for the type MockConfigurer
func (_mock *MockConfigurer[T]) Config() T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func() T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// MockConfigurer_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockConfigurer_Config_Call[T any] struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockConfigurer_Expecter[T]) Config() *MockConfigurer_Config_Call[T] {
	return &MockConfigurer_Config_Call[T]{Call: _e.mock.On("Config")}
}

func (_c *MockConfigurer_Config_Call[T]) Run(run func()) *MockConfigurer_Config_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurer_Config_Call[T]) Return(v T) *MockConfigurer_Config_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConfigurer_Config_Call[T]) RunAndReturn(run func() T) *MockConfigurer_Config_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ConfigListeners provides a mock function for the type MockConfigurer
func (_mock *MockConfigurer[T]) ConfigListeners() []ConfigurerListener[T] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigListeners")
	}

	var r0 []ConfigurerListener[T]
	if returnFunc, ok := ret.Get(0).(func() []ConfigurerListener[T]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConfigurerListener[T])
		}
	}
	return r0
}

// MockConfigurer_ConfigListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigListeners'
type MockConfigurer_ConfigListeners_Call[T any] struct {
	*mock.Call
}

// ConfigListeners is a helper method to define mock.On call
func (_e *MockConfigurer_Expecter[T]) ConfigListeners() *MockConfigurer_ConfigListeners_Call[T] {
	return &MockConfigurer_ConfigListeners_Call[T]{Call: _e.mock.On("ConfigListeners")}
}

func (_c *MockConfigurer_ConfigListeners_Call[T]) Run(run func()) *MockConfigurer_ConfigListeners_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurer_ConfigListeners_Call[T]) Return(configurerListeners []ConfigurerListener[T]) *MockConfigurer_ConfigListeners_Call[T] {
	_c.Call.Return(configurerListeners)
	return _c
}

func (_c *MockConfigurer_ConfigListeners_Call[T]) RunAndReturn(run func() []ConfigurerListener[T]) *MockConfigurer_ConfigListeners_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type MockConfigurer
func (_mock *MockConfigurer[T]) Configure(config T) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(T) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigurer_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockConfigurer_Configure_Call[T any] struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - config T
func (_e *MockConfigurer_Expecter[T]) Configure(config any) *MockConfigurer_Configure_Call[T] {
	return &MockConfigurer_Configure_Call[T]{Call: _e.mock.On("Configure", config)}
}

func (_c *MockConfigurer_Configure_Call[T]) Run(run func(config T)) *MockConfigurer_Configure_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurer_Configure_Call[T]) Return(err error) *MockConfigurer_Configure_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigurer_Configure_Call[T]) RunAndReturn(run func(config T) error) *MockConfigurer_Configure_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockConfigurer
func (_mock *MockConfigurer[T]) Subscribe(listener ConfigurerListener[T]) {
	_mock.Called(listener)
	return
}

// MockConfigurer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockConfigurer_Subscribe_Call[T any] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener ConfigurerListener[T]
func (_e *MockConfigurer_Expecter[T]) Subscribe(listener any) *MockConfigurer_Subscribe_Call[T] {
	return &MockConfigurer_Subscribe_Call[T]{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *MockConfigurer_Subscribe_Call[T]) Run(run func(listener ConfigurerListener[T])) *MockConfigurer_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ConfigurerListener[T]
		if args[0] != nil {
			arg0 = args[0].(ConfigurerListener[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurer_Subscribe_Call[T]) Return() *MockConfigurer_Subscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurer_Subscribe_Call[T]) RunAndReturn(run func(listener ConfigurerListener[T])) *MockConfigurer_Subscribe_Call[T] {
	_c.Run(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockConfigurer
func (_mock *MockConfigurer[T]) Unsubscribe(listener ConfigurerListener[T]) {
	_mock.Called(listener)
	return
}

// MockConfigurer_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockConfigurer_Unsubscribe_Call[T any] struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - listener ConfigurerListener[T]
func (_e *MockConfigurer_Expecter[T]) Unsubscribe(listener any) *MockConfigurer_Unsubscribe_Call[T] {
	return &MockConfigurer_Unsubscribe_Call[T]{Call: _e.mock.On("Unsubscribe", listener)}
}

func (_c *MockConfigurer_Unsubscribe_Call[T]) Run(run func(listener ConfigurerListener[T])) *MockConfigurer_Unsubscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ConfigurerListener[T]
		if args[0] != nil {
			arg0 = args[0].(ConfigurerListener[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurer_Unsubscribe_Call[T]) Return() *MockConfigurer_Unsubscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurer_Unsubscribe_Call[T]) RunAndReturn(run func(listener ConfigurerListener[T])) *MockConfigurer_Unsubscribe_Call[T] {
	_c.Run(run)
	return _c
}
