// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package web

import (
	"net/http"
	"pan/pkg/config"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWebRouter creates a new instance of MockWebRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebRouter {
	mock := &MockWebRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebRouter is an autogenerated mock type for the WebRouter type
type MockWebRouter struct {
	mock.Mock
}

type MockWebRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebRouter) EXPECT() *MockWebRouter_Expecter {
	return &MockWebRouter_Expecter{mock: &_m.Mock}
}

// Any provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) Any(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Any")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_Any_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Any'
type MockWebRouter_Any_Call struct {
	*mock.Call
}

// Any is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) Any(s any, handlerFuncs ...any) *MockWebRouter_Any_Call {
	return &MockWebRouter_Any_Call{Call: _e.mock.On("Any",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_Any_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_Any_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_Any_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_Any_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_Any_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_Any_Call {
	_c.Call.Return(run)
	return _c
}

// DELETE provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) DELETE(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DELETE")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_DELETE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DELETE'
type MockWebRouter_DELETE_Call struct {
	*mock.Call
}

// DELETE is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) DELETE(s any, handlerFuncs ...any) *MockWebRouter_DELETE_Call {
	return &MockWebRouter_DELETE_Call{Call: _e.mock.On("DELETE",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_DELETE_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_DELETE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_DELETE_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_DELETE_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_DELETE_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_DELETE_Call {
	_c.Call.Return(run)
	return _c
}

// GET provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) GET(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GET")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_GET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GET'
type MockWebRouter_GET_Call struct {
	*mock.Call
}

// GET is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) GET(s any, handlerFuncs ...any) *MockWebRouter_GET_Call {
	return &MockWebRouter_GET_Call{Call: _e.mock.On("GET",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_GET_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_GET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_GET_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_GET_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_GET_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_GET_Call {
	_c.Call.Return(run)
	return _c
}

// Group provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) Group(s string, handlerFuncs ...gin.HandlerFunc) *gin.RouterGroup {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 *gin.RouterGroup
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) *gin.RouterGroup); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gin.RouterGroup)
		}
	}
	return r0
}

// MockWebRouter_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockWebRouter_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) Group(s any, handlerFuncs ...any) *MockWebRouter_Group_Call {
	return &MockWebRouter_Group_Call{Call: _e.mock.On("Group",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_Group_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_Group_Call) Return(routerGroup *gin.RouterGroup) *MockWebRouter_Group_Call {
	_c.Call.Return(routerGroup)
	return _c
}

func (_c *MockWebRouter_Group_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) *gin.RouterGroup) *MockWebRouter_Group_Call {
	_c.Call.Return(run)
	return _c
}

// HEAD provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) HEAD(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HEAD")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_HEAD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HEAD'
type MockWebRouter_HEAD_Call struct {
	*mock.Call
}

// HEAD is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) HEAD(s any, handlerFuncs ...any) *MockWebRouter_HEAD_Call {
	return &MockWebRouter_HEAD_Call{Call: _e.mock.On("HEAD",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_HEAD_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_HEAD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_HEAD_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_HEAD_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_HEAD_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_HEAD_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) Handle(s string, s1 string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s, s1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, s1, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockWebRouter_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - s string
//   - s1 string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) Handle(s any, s1 any, handlerFuncs ...any) *MockWebRouter_Handle_Call {
	return &MockWebRouter_Handle_Call{Call: _e.mock.On("Handle",
		append([]any{s, s1}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_Handle_Call) Run(run func(s string, s1 string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWebRouter_Handle_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_Handle_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_Handle_Call) RunAndReturn(run func(s string, s1 string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) Match(strings []string, s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, strings, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func([]string, string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(strings, s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockWebRouter_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - strings []string
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) Match(strings any, s any, handlerFuncs ...any) *MockWebRouter_Match_Call {
	return &MockWebRouter_Match_Call{Call: _e.mock.On("Match",
		append([]any{strings, s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_Match_Call) Run(run func(strings []string, s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWebRouter_Match_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_Match_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_Match_Call) RunAndReturn(run func(strings []string, s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_Match_Call {
	_c.Call.Return(run)
	return _c
}

// OPTIONS provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) OPTIONS(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OPTIONS")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_OPTIONS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OPTIONS'
type MockWebRouter_OPTIONS_Call struct {
	*mock.Call
}

// OPTIONS is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) OPTIONS(s any, handlerFuncs ...any) *MockWebRouter_OPTIONS_Call {
	return &MockWebRouter_OPTIONS_Call{Call: _e.mock.On("OPTIONS",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_OPTIONS_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_OPTIONS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_OPTIONS_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_OPTIONS_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_OPTIONS_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_OPTIONS_Call {
	_c.Call.Return(run)
	return _c
}

// PATCH provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) PATCH(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PATCH")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_PATCH_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PATCH'
type MockWebRouter_PATCH_Call struct {
	*mock.Call
}

// PATCH is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) PATCH(s any, handlerFuncs ...any) *MockWebRouter_PATCH_Call {
	return &MockWebRouter_PATCH_Call{Call: _e.mock.On("PATCH",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_PATCH_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_PATCH_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_PATCH_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_PATCH_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_PATCH_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_PATCH_Call {
	_c.Call.Return(run)
	return _c
}

// POST provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) POST(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for POST")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_POST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'POST'
type MockWebRouter_POST_Call struct {
	*mock.Call
}

// POST is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) POST(s any, handlerFuncs ...any) *MockWebRouter_POST_Call {
	return &MockWebRouter_POST_Call{Call: _e.mock.On("POST",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_POST_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_POST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_POST_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_POST_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_POST_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_POST_Call {
	_c.Call.Return(run)
	return _c
}

// PUT provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) PUT(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, s)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PUT")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, ...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(s, handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_PUT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PUT'
type MockWebRouter_PUT_Call struct {
	*mock.Call
}

// PUT is a helper method to define mock.On call
//   - s string
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) PUT(s any, handlerFuncs ...any) *MockWebRouter_PUT_Call {
	return &MockWebRouter_PUT_Call{Call: _e.mock.On("PUT",
		append([]any{s}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_PUT_Call) Run(run func(s string, handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_PUT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockWebRouter_PUT_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_PUT_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_PUT_Call) RunAndReturn(run func(s string, handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_PUT_Call {
	_c.Call.Return(run)
	return _c
}

// Static provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) Static(s string, s1 string) gin.IRoutes {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Static")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, string) gin.IRoutes); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_Static_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Static'
type MockWebRouter_Static_Call struct {
	*mock.Call
}

// Static is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockWebRouter_Expecter) Static(s any, s1 any) *MockWebRouter_Static_Call {
	return &MockWebRouter_Static_Call{Call: _e.mock.On("Static", s, s1)}
}

func (_c *MockWebRouter_Static_Call) Run(run func(s string, s1 string)) *MockWebRouter_Static_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebRouter_Static_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_Static_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_Static_Call) RunAndReturn(run func(s string, s1 string) gin.IRoutes) *MockWebRouter_Static_Call {
	_c.Call.Return(run)
	return _c
}

// StaticFS provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) StaticFS(s string, fileSystem http.FileSystem) gin.IRoutes {
	ret := _mock.Called(s, fileSystem)

	if len(ret) == 0 {
		panic("no return value specified for StaticFS")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, http.FileSystem) gin.IRoutes); ok {
		r0 = returnFunc(s, fileSystem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_StaticFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaticFS'
type MockWebRouter_StaticFS_Call struct {
	*mock.Call
}

// StaticFS is a helper method to define mock.On call
//   - s string
//   - fileSystem http.FileSystem
func (_e *MockWebRouter_Expecter) StaticFS(s any, fileSystem any) *MockWebRouter_StaticFS_Call {
	return &MockWebRouter_StaticFS_Call{Call: _e.mock.On("StaticFS", s, fileSystem)}
}

func (_c *MockWebRouter_StaticFS_Call) Run(run func(s string, fileSystem http.FileSystem)) *MockWebRouter_StaticFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.FileSystem
		if args[1] != nil {
			arg1 = args[1].(http.FileSystem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebRouter_StaticFS_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_StaticFS_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_StaticFS_Call) RunAndReturn(run func(s string, fileSystem http.FileSystem) gin.IRoutes) *MockWebRouter_StaticFS_Call {
	_c.Call.Return(run)
	return _c
}

// StaticFile provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) StaticFile(s string, s1 string) gin.IRoutes {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for StaticFile")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, string) gin.IRoutes); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_StaticFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaticFile'
type MockWebRouter_StaticFile_Call struct {
	*mock.Call
}

// StaticFile is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockWebRouter_Expecter) StaticFile(s any, s1 any) *MockWebRouter_StaticFile_Call {
	return &MockWebRouter_StaticFile_Call{Call: _e.mock.On("StaticFile", s, s1)}
}

func (_c *MockWebRouter_StaticFile_Call) Run(run func(s string, s1 string)) *MockWebRouter_StaticFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebRouter_StaticFile_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_StaticFile_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_StaticFile_Call) RunAndReturn(run func(s string, s1 string) gin.IRoutes) *MockWebRouter_StaticFile_Call {
	_c.Call.Return(run)
	return _c
}

// StaticFileFS provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) StaticFileFS(s string, s1 string, fileSystem http.FileSystem) gin.IRoutes {
	ret := _mock.Called(s, s1, fileSystem)

	if len(ret) == 0 {
		panic("no return value specified for StaticFileFS")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(string, string, http.FileSystem) gin.IRoutes); ok {
		r0 = returnFunc(s, s1, fileSystem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_StaticFileFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaticFileFS'
type MockWebRouter_StaticFileFS_Call struct {
	*mock.Call
}

// StaticFileFS is a helper method to define mock.On call
//   - s string
//   - s1 string
//   - fileSystem http.FileSystem
func (_e *MockWebRouter_Expecter) StaticFileFS(s any, s1 any, fileSystem any) *MockWebRouter_StaticFileFS_Call {
	return &MockWebRouter_StaticFileFS_Call{Call: _e.mock.On("StaticFileFS", s, s1, fileSystem)}
}

func (_c *MockWebRouter_StaticFileFS_Call) Run(run func(s string, s1 string, fileSystem http.FileSystem)) *MockWebRouter_StaticFileFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 http.FileSystem
		if args[2] != nil {
			arg2 = args[2].(http.FileSystem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebRouter_StaticFileFS_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_StaticFileFS_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_StaticFileFS_Call) RunAndReturn(run func(s string, s1 string, fileSystem http.FileSystem) gin.IRoutes) *MockWebRouter_StaticFileFS_Call {
	_c.Call.Return(run)
	return _c
}

// Use provides a mock function for the type MockWebRouter
func (_mock *MockWebRouter) Use(handlerFuncs ...gin.HandlerFunc) gin.IRoutes {
	// gin.HandlerFunc
	_va := make([]any, len(handlerFuncs))
	for _i := range handlerFuncs {
		_va[_i] = handlerFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Use")
	}

	var r0 gin.IRoutes
	if returnFunc, ok := ret.Get(0).(func(...gin.HandlerFunc) gin.IRoutes); ok {
		r0 = returnFunc(handlerFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRoutes)
		}
	}
	return r0
}

// MockWebRouter_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockWebRouter_Use_Call struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - handlerFuncs ...gin.HandlerFunc
func (_e *MockWebRouter_Expecter) Use(handlerFuncs ...any) *MockWebRouter_Use_Call {
	return &MockWebRouter_Use_Call{Call: _e.mock.On("Use",
		append([]any{}, handlerFuncs...)...)}
}

func (_c *MockWebRouter_Use_Call) Run(run func(handlerFuncs ...gin.HandlerFunc)) *MockWebRouter_Use_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []gin.HandlerFunc
		variadicArgs := make([]gin.HandlerFunc, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(gin.HandlerFunc)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockWebRouter_Use_Call) Return(iRoutes gin.IRoutes) *MockWebRouter_Use_Call {
	_c.Call.Return(iRoutes)
	return _c
}

func (_c *MockWebRouter_Use_Call) RunAndReturn(run func(handlerFuncs ...gin.HandlerFunc) gin.IRoutes) *MockWebRouter_Use_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebConfig creates a new instance of MockWebConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebConfig {
	mock := &MockWebConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebConfig is an autogenerated mock type for the WebConfig type
type MockWebConfig struct {
	mock.Mock
}

type MockWebConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebConfig) EXPECT() *MockWebConfig_Expecter {
	return &MockWebConfig_Expecter{mock: &_m.Mock}
}

// Addr provides a mock function for the type MockWebConfig
func (_mock *MockWebConfig) Addr() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWebConfig_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type MockWebConfig_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *MockWebConfig_Expecter) Addr() *MockWebConfig_Addr_Call {
	return &MockWebConfig_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *MockWebConfig_Addr_Call) Run(run func()) *MockWebConfig_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebConfig_Addr_Call) Return(s string) *MockWebConfig_Addr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWebConfig_Addr_Call) RunAndReturn(run func() string) *MockWebConfig_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebConfigListener creates a new instance of MockWebConfigListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebConfigListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebConfigListener {
	mock := &MockWebConfigListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebConfigListener is an autogenerated mock type for the WebConfigListener type
type MockWebConfigListener struct {
	mock.Mock
}

type MockWebConfigListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebConfigListener) EXPECT() *MockWebConfigListener_Expecter {
	return &MockWebConfigListener_Expecter{mock: &_m.Mock}
}

// OnConfigUpdated provides a mock function for the type MockWebConfigListener
func (_mock *MockWebConfigListener) OnConfigUpdated(config WebConfig) {
	_mock.Called(config)
	return
}

// MockWebConfigListener_OnConfigUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConfigUpdated'
type MockWebConfigListener_OnConfigUpdated_Call struct {
	*mock.Call
}

// OnConfigUpdated is a helper method to define mock.On call
//   - config WebConfig
func (_e *MockWebConfigListener_Expecter) OnConfigUpdated(config any) *MockWebConfigListener_OnConfigUpdated_Call {
	return &MockWebConfigListener_OnConfigUpdated_Call{Call: _e.mock.On("OnConfigUpdated", config)}
}

func (_c *MockWebConfigListener_OnConfigUpdated_Call) Run(run func(config WebConfig)) *MockWebConfigListener_OnConfigUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 WebConfig
		if args[0] != nil {
			arg0 = args[0].(WebConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebConfigListener_OnConfigUpdated_Call) Return() *MockWebConfigListener_OnConfigUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebConfigListener_OnConfigUpdated_Call) RunAndReturn(run func(config WebConfig)) *MockWebConfigListener_OnConfigUpdated_Call {
	_c.Run(run)
	return _c
}

// NewMockWebConfigurer creates a new instance of MockWebConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebConfigurer {
	mock := &MockWebConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebConfigurer is an autogenerated mock type for the WebConfigurer type
type MockWebConfigurer struct {
	mock.Mock
}

type MockWebConfigurer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebConfigurer) EXPECT() *MockWebConfigurer_Expecter {
	return &MockWebConfigurer_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockWebConfigurer
func (_mock *MockWebConfigurer) Config() WebConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 WebConfig
	if returnFunc, ok := ret.Get(0).(func() WebConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(WebConfig)
		}
	}
	return r0
}

// MockWebConfigurer_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockWebConfigurer_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockWebConfigurer_Expecter) Config() *MockWebConfigurer_Config_Call {
	return &MockWebConfigurer_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockWebConfigurer_Config_Call) Run(run func()) *MockWebConfigurer_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebConfigurer_Config_Call) Return(webConfig WebConfig) *MockWebConfigurer_Config_Call {
	_c.Call.Return(webConfig)
	return _c
}

func (_c *MockWebConfigurer_Config_Call) RunAndReturn(run func() WebConfig) *MockWebConfigurer_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigListeners provides a mock function for the type MockWebConfigurer
func (_mock *MockWebConfigurer) ConfigListeners() []config.ConfigurerListener[WebConfig] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigListeners")
	}

	var r0 []config.ConfigurerListener[WebConfig]
	if returnFunc, ok := ret.Get(0).(func() []config.ConfigurerListener[WebConfig]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ConfigurerListener[WebConfig])
		}
	}
	return r0
}

// MockWebConfigurer_ConfigListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigListeners'
type MockWebConfigurer_ConfigListeners_Call struct {
	*mock.Call
}

// ConfigListeners is a helper method to define mock.On call
func (_e *MockWebConfigurer_Expecter) ConfigListeners() *MockWebConfigurer_ConfigListeners_Call {
	return &MockWebConfigurer_ConfigListeners_Call{Call: _e.mock.On("ConfigListeners")}
}

func (_c *MockWebConfigurer_ConfigListeners_Call) Run(run func()) *MockWebConfigurer_ConfigListeners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebConfigurer_ConfigListeners_Call) Return(configurerListeners []config.ConfigurerListener[WebConfig]) *MockWebConfigurer_ConfigListeners_Call {
	_c.Call.Return(configurerListeners)
	return _c
}

func (_c *MockWebConfigurer_ConfigListeners_Call) RunAndReturn(run func() []config.ConfigurerListener[WebConfig]) *MockWebConfigurer_ConfigListeners_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type MockWebConfigurer
func (_mock *MockWebConfigurer) Configure(config1 WebConfig) error {
	ret := _mock.Called(config1)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(WebConfig) error); ok {
		r0 = returnFunc(config1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebConfigurer_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockWebConfigurer_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - config1 WebConfig
func (_e *MockWebConfigurer_Expecter) Configure(config1 any) *MockWebConfigurer_Configure_Call {
	return &MockWebConfigurer_Configure_Call{Call: _e.mock.On("Configure", config1)}
}

func (_c *MockWebConfigurer_Configure_Call) Run(run func(config1 WebConfig)) *MockWebConfigurer_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 WebConfig
		if args[0] != nil {
			arg0 = args[0].(WebConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebConfigurer_Configure_Call) Return(err error) *MockWebConfigurer_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebConfigurer_Configure_Call) RunAndReturn(run func(config1 WebConfig) error) *MockWebConfigurer_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockWebConfigurer
func (_mock *MockWebConfigurer) Subscribe(listener config.ConfigurerListener[WebConfig]) {
	_mock.Called(listener)
	return
}

// MockWebConfigurer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockWebConfigurer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[WebConfig]
func (_e *MockWebConfigurer_Expecter) Subscribe(listener any) *MockWebConfigurer_Subscribe_Call {
	return &MockWebConfigurer_Subscribe_Call{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *MockWebConfigurer_Subscribe_Call) Run(run func(listener config.ConfigurerListener[WebConfig])) *MockWebConfigurer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[WebConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[WebConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebConfigurer_Subscribe_Call) Return() *MockWebConfigurer_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebConfigurer_Subscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[WebConfig])) *MockWebConfigurer_Subscribe_Call {
	_c.Run(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockWebConfigurer
func (_mock *MockWebConfigurer) Unsubscribe(listener config.ConfigurerListener[WebConfig]) {
	_mock.Called(listener)
	return
}

// MockWebConfigurer_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockWebConfigurer_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - listener config.ConfigurerListener[WebConfig]
func (_e *MockWebConfigurer_Expecter) Unsubscribe(listener any) *MockWebConfigurer_Unsubscribe_Call {
	return &MockWebConfigurer_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", listener)}
}

func (_c *MockWebConfigurer_Unsubscribe_Call) Run(run func(listener config.ConfigurerListener[WebConfig])) *MockWebConfigurer_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ConfigurerListener[WebConfig]
		if args[0] != nil {
			arg0 = args[0].(config.ConfigurerListener[WebConfig])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebConfigurer_Unsubscribe_Call) Return() *MockWebConfigurer_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebConfigurer_Unsubscribe_Call) RunAndReturn(run func(listener config.ConfigurerListener[WebConfig])) *MockWebConfigurer_Unsubscribe_Call {
	_c.Run(run)
	return _c
}

// NewMockWebAppModule creates a new instance of MockWebAppModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebAppModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebAppModule {
	mock := &MockWebAppModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebAppModule is an autogenerated mock type for the WebAppModule type
type MockWebAppModule struct {
	mock.Mock
}

type MockWebAppModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebAppModule) EXPECT() *MockWebAppModule_Expecter {
	return &MockWebAppModule_Expecter{mock: &_m.Mock}
}

// SetupToWeb provides a mock function for the type MockWebAppModule
func (_mock *MockWebAppModule) SetupToWeb(v WebApp) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for SetupToWeb")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(WebApp) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebAppModule_SetupToWeb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToWeb'
type MockWebAppModule_SetupToWeb_Call struct {
	*mock.Call
}

// SetupToWeb is a helper method to define mock.On call
//   - v WebApp
func (_e *MockWebAppModule_Expecter) SetupToWeb(v any) *MockWebAppModule_SetupToWeb_Call {
	return &MockWebAppModule_SetupToWeb_Call{Call: _e.mock.On("SetupToWeb", v)}
}

func (_c *MockWebAppModule_SetupToWeb_Call) Run(run func(v WebApp)) *MockWebAppModule_SetupToWeb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 WebApp
		if args[0] != nil {
			arg0 = args[0].(WebApp)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebAppModule_SetupToWeb_Call) Return(err error) *MockWebAppModule_SetupToWeb_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebAppModule_SetupToWeb_Call) RunAndReturn(run func(v WebApp) error) *MockWebAppModule_SetupToWeb_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebController creates a new instance of MockWebController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebController {
	mock := &MockWebController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebController is an autogenerated mock type for the WebController type
type MockWebController struct {
	mock.Mock
}

type MockWebController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebController) EXPECT() *MockWebController_Expecter {
	return &MockWebController_Expecter{mock: &_m.Mock}
}

// SetupToWeb provides a mock function for the type MockWebController
func (_mock *MockWebController) SetupToWeb(v WebRouter) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for SetupToWeb")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(WebRouter) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebController_SetupToWeb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToWeb'
type MockWebController_SetupToWeb_Call struct {
	*mock.Call
}

// SetupToWeb is a helper method to define mock.On call
//   - v WebRouter
func (_e *MockWebController_Expecter) SetupToWeb(v any) *MockWebController_SetupToWeb_Call {
	return &MockWebController_SetupToWeb_Call{Call: _e.mock.On("SetupToWeb", v)}
}

func (_c *MockWebController_SetupToWeb_Call) Run(run func(v WebRouter)) *MockWebController_SetupToWeb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 WebRouter
		if args[0] != nil {
			arg0 = args[0].(WebRouter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebController_SetupToWeb_Call) Return(err error) *MockWebController_SetupToWeb_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebController_SetupToWeb_Call) RunAndReturn(run func(v WebRouter) error) *MockWebController_SetupToWeb_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebControllerProvider creates a new instance of MockWebControllerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebControllerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebControllerProvider {
	mock := &MockWebControllerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebControllerProvider is an autogenerated mock type for the WebControllerProvider type
type MockWebControllerProvider struct {
	mock.Mock
}

type MockWebControllerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebControllerProvider) EXPECT() *MockWebControllerProvider_Expecter {
	return &MockWebControllerProvider_Expecter{mock: &_m.Mock}
}

// WebControllers provides a mock function for the type MockWebControllerProvider
func (_mock *MockWebControllerProvider) WebControllers() []WebController {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebControllers")
	}

	var r0 []WebController
	if returnFunc, ok := ret.Get(0).(func() []WebController); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WebController)
		}
	}
	return r0
}

// MockWebControllerProvider_WebControllers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebControllers'
type MockWebControllerProvider_WebControllers_Call struct {
	*mock.Call
}

// WebControllers is a helper method to define mock.On call
func (_e *MockWebControllerProvider_Expecter) WebControllers() *MockWebControllerProvider_WebControllers_Call {
	return &MockWebControllerProvider_WebControllers_Call{Call: _e.mock.On("WebControllers")}
}

func (_c *MockWebControllerProvider_WebControllers_Call) Run(run func()) *MockWebControllerProvider_WebControllers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebControllerProvider_WebControllers_Call) Return(webControllers []WebController) *MockWebControllerProvider_WebControllers_Call {
	_c.Call.Return(webControllers)
	return _c
}

func (_c *MockWebControllerProvider_WebControllers_Call) RunAndReturn(run func() []WebController) *MockWebControllerProvider_WebControllers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebRouteModule creates a new instance of MockWebRouteModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebRouteModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebRouteModule {
	mock := &MockWebRouteModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebRouteModule is an autogenerated mock type for the WebRouteModule type
type MockWebRouteModule struct {
	mock.Mock
}

type MockWebRouteModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebRouteModule) EXPECT() *MockWebRouteModule_Expecter {
	return &MockWebRouteModule_Expecter{mock: &_m.Mock}
}

// WebRouteName provides a mock function for the type MockWebRouteModule
func (_mock *MockWebRouteModule) WebRouteName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebRouteName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWebRouteModule_WebRouteName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebRouteName'
type MockWebRouteModule_WebRouteName_Call struct {
	*mock.Call
}

// WebRouteName is a helper method to define mock.On call
func (_e *MockWebRouteModule_Expecter) WebRouteName() *MockWebRouteModule_WebRouteName_Call {
	return &MockWebRouteModule_WebRouteName_Call{Call: _e.mock.On("WebRouteName")}
}

func (_c *MockWebRouteModule_WebRouteName_Call) Run(run func()) *MockWebRouteModule_WebRouteName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebRouteModule_WebRouteName_Call) Return(s string) *MockWebRouteModule_WebRouteName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWebRouteModule_WebRouteName_Call) RunAndReturn(run func() string) *MockWebRouteModule_WebRouteName_Call {
	_c.Call.Return(run)
	return _c
}
