syntax = "proto3";
package user;

option go_package = "internal/user;user";

message RemoteUserMeta{
    string Code = 1; 
    string GenesisSignature = 2;
    string Signature = 3;
    uint64 Height = 4;
}

message RemoteUser {
    string Code = 1; 
    string GenesisSignature = 2;
    string Signature = 3;
    uint64 Height = 4;
    bytes UserKey = 5;

    string Name = 6;
    string Memo = 7;
}

message RemoteUserConsensus {
    string Signature = 1;
    string PreSignature = 2;

    bytes PeerID = 3;
    bytes PeerSignature = 4;

    uint64 Timestamp = 5;
    bytes UserKey = 6;
    uint64 Height = 7;

    bytes PassphraseSignature = 8;
    bytes OldPassphrase = 9;

    bytes InfoSignature = 10;
    bytes DeviceSignature = 11;
    bytes ExtraSignature = 12;
}

message RemoteUserSecret {
    bytes UserKey = 1;
    bytes UserSecretKey = 2;
}

message RemoteUserDevice {
    string PeerID = 1;
    bytes Level = 2;
    bytes PeerSignature = 3;
    bool Enabled = 4;

    uint64 Height = 5;
    bytes HeightSignature = 6;
}

message RemoteUserExtra {
    uint64 SerialNumber = 1;
    bytes Signature = 2;
}