// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: extfs/proto/remote_block.proto

package remoteblock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteBlockSelectCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID     int32  `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	ParentPath string `protobuf:"bytes,2,opt,name=ParentPath,proto3" json:"ParentPath,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Offset     int64  `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit      int64  `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *RemoteBlockSelectCondition) Reset() {
	*x = RemoteBlockSelectCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extfs_proto_remote_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteBlockSelectCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteBlockSelectCondition) ProtoMessage() {}

func (x *RemoteBlockSelectCondition) ProtoReflect() protoreflect.Message {
	mi := &file_extfs_proto_remote_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteBlockSelectCondition.ProtoReflect.Descriptor instead.
func (*RemoteBlockSelectCondition) Descriptor() ([]byte, []int) {
	return file_extfs_proto_remote_block_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteBlockSelectCondition) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *RemoteBlockSelectCondition) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *RemoteBlockSelectCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteBlockSelectCondition) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RemoteBlockSelectCondition) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_extfs_proto_remote_block_proto protoreflect.FileDescriptor

var file_extfs_proto_remote_block_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x65, 0x78, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x96, 0x01,
	0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x20, 0x5a, 0x1e, 0x65, 0x78, 0x74, 0x66, 0x73, 0x2f,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x3b, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extfs_proto_remote_block_proto_rawDescOnce sync.Once
	file_extfs_proto_remote_block_proto_rawDescData = file_extfs_proto_remote_block_proto_rawDesc
)

func file_extfs_proto_remote_block_proto_rawDescGZIP() []byte {
	file_extfs_proto_remote_block_proto_rawDescOnce.Do(func() {
		file_extfs_proto_remote_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_extfs_proto_remote_block_proto_rawDescData)
	})
	return file_extfs_proto_remote_block_proto_rawDescData
}

var file_extfs_proto_remote_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extfs_proto_remote_block_proto_goTypes = []interface{}{
	(*RemoteBlockSelectCondition)(nil), // 0: remoteblock.RemoteBlockSelectCondition
}
var file_extfs_proto_remote_block_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extfs_proto_remote_block_proto_init() }
func file_extfs_proto_remote_block_proto_init() {
	if File_extfs_proto_remote_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extfs_proto_remote_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteBlockSelectCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extfs_proto_remote_block_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extfs_proto_remote_block_proto_goTypes,
		DependencyIndexes: file_extfs_proto_remote_block_proto_depIdxs,
		MessageInfos:      file_extfs_proto_remote_block_proto_msgTypes,
	}.Build()
	File_extfs_proto_remote_block_proto = out.File
	file_extfs_proto_remote_block_proto_rawDesc = nil
	file_extfs_proto_remote_block_proto_goTypes = nil
	file_extfs_proto_remote_block_proto_depIdxs = nil
}
