// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package injection

import (
	"reflect"

	mock "github.com/stretchr/testify/mock"
)

// NewMockComponent creates a new instance of MockComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponent {
	mock := &MockComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComponent is an autogenerated mock type for the Component type
type MockComponent struct {
	mock.Mock
}

type MockComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponent) EXPECT() *MockComponent_Expecter {
	return &MockComponent_Expecter{mock: &_m.Mock}
}

// Scope provides a mock function for the type MockComponent
func (_mock *MockComponent) Scope() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scope")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockComponent_Scope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scope'
type MockComponent_Scope_Call struct {
	*mock.Call
}

// Scope is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Scope() *MockComponent_Scope_Call {
	return &MockComponent_Scope_Call{Call: _e.mock.On("Scope")}
}

func (_c *MockComponent_Scope_Call) Run(run func()) *MockComponent_Scope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Scope_Call) Return(s string) *MockComponent_Scope_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockComponent_Scope_Call) RunAndReturn(run func() string) *MockComponent_Scope_Call {
	_c.Call.Return(run)
	return _c
}

// Target provides a mock function for the type MockComponent
func (_mock *MockComponent) Target() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Target")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockComponent_Target_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Target'
type MockComponent_Target_Call struct {
	*mock.Call
}

// Target is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Target() *MockComponent_Target_Call {
	return &MockComponent_Target_Call{Call: _e.mock.On("Target")}
}

func (_c *MockComponent_Target_Call) Run(run func()) *MockComponent_Target_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Target_Call) Return(ifaceVal interface{}) *MockComponent_Target_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockComponent_Target_Call) RunAndReturn(run func() interface{}) *MockComponent_Target_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockComponent
func (_mock *MockComponent) Type() reflect.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 reflect.Type
	if returnFunc, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}
	return r0
}

// MockComponent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockComponent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Type() *MockComponent_Type_Call {
	return &MockComponent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockComponent_Type_Call) Run(run func()) *MockComponent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Type_Call) Return(typeParam reflect.Type) *MockComponent_Type_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *MockComponent_Type_Call) RunAndReturn(run func() reflect.Type) *MockComponent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentProvider creates a new instance of MockComponentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentProvider {
	mock := &MockComponentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComponentProvider is an autogenerated mock type for the ComponentProvider type
type MockComponentProvider struct {
	mock.Mock
}

type MockComponentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentProvider) EXPECT() *MockComponentProvider_Expecter {
	return &MockComponentProvider_Expecter{mock: &_m.Mock}
}

// Components provides a mock function for the type MockComponentProvider
func (_mock *MockComponentProvider) Components() []Component {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Components")
	}

	var r0 []Component
	if returnFunc, ok := ret.Get(0).(func() []Component); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Component)
		}
	}
	return r0
}

// MockComponentProvider_Components_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Components'
type MockComponentProvider_Components_Call struct {
	*mock.Call
}

// Components is a helper method to define mock.On call
func (_e *MockComponentProvider_Expecter) Components() *MockComponentProvider_Components_Call {
	return &MockComponentProvider_Components_Call{Call: _e.mock.On("Components")}
}

func (_c *MockComponentProvider_Components_Call) Run(run func()) *MockComponentProvider_Components_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentProvider_Components_Call) Return(components []Component) *MockComponentProvider_Components_Call {
	_c.Call.Return(components)
	return _c
}

func (_c *MockComponentProvider_Components_Call) RunAndReturn(run func() []Component) *MockComponentProvider_Components_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentStoreProvider creates a new instance of MockComponentStoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentStoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentStoreProvider {
	mock := &MockComponentStoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComponentStoreProvider is an autogenerated mock type for the ComponentStoreProvider type
type MockComponentStoreProvider struct {
	mock.Mock
}

type MockComponentStoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentStoreProvider) EXPECT() *MockComponentStoreProvider_Expecter {
	return &MockComponentStoreProvider_Expecter{mock: &_m.Mock}
}

// ComponentStore provides a mock function for the type MockComponentStoreProvider
func (_mock *MockComponentStoreProvider) ComponentStore() ComponentStore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ComponentStore")
	}

	var r0 ComponentStore
	if returnFunc, ok := ret.Get(0).(func() ComponentStore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ComponentStore)
		}
	}
	return r0
}

// MockComponentStoreProvider_ComponentStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentStore'
type MockComponentStoreProvider_ComponentStore_Call struct {
	*mock.Call
}

// ComponentStore is a helper method to define mock.On call
func (_e *MockComponentStoreProvider_Expecter) ComponentStore() *MockComponentStoreProvider_ComponentStore_Call {
	return &MockComponentStoreProvider_ComponentStore_Call{Call: _e.mock.On("ComponentStore")}
}

func (_c *MockComponentStoreProvider_ComponentStore_Call) Run(run func()) *MockComponentStoreProvider_ComponentStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentStoreProvider_ComponentStore_Call) Return(v ComponentStore) *MockComponentStoreProvider_ComponentStore_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockComponentStoreProvider_ComponentStore_Call) RunAndReturn(run func() ComponentStore) *MockComponentStoreProvider_ComponentStore_Call {
	_c.Call.Return(run)
	return _c
}
