// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"io"
	"pan/pkg/servlet"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAppServletRouter creates a new instance of MockAppServletRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppServletRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppServletRouter {
	mock := &MockAppServletRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppServletRouter is an autogenerated mock type for the AppServletRouter type
type MockAppServletRouter struct {
	mock.Mock
}

type MockAppServletRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppServletRouter) EXPECT() *MockAppServletRouter_Expecter {
	return &MockAppServletRouter_Expecter{mock: &_m.Mock}
}

// Default provides a mock function for the type MockAppServletRouter
func (_mock *MockAppServletRouter) Default(handleFuncs ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext] {
	// servlet.HandleFunc[AppServletContext]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Default")
	}

	var r0 servlet.HandleGroup[AppServletContext]
	if returnFunc, ok := ret.Get(0).(func(...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext]); ok {
		r0 = returnFunc(handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[AppServletContext])
		}
	}
	return r0
}

// MockAppServletRouter_Default_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Default'
type MockAppServletRouter_Default_Call struct {
	*mock.Call
}

// Default is a helper method to define mock.On call
//   - handleFuncs ...servlet.HandleFunc[AppServletContext]
func (_e *MockAppServletRouter_Expecter) Default(handleFuncs ...any) *MockAppServletRouter_Default_Call {
	return &MockAppServletRouter_Default_Call{Call: _e.mock.On("Default",
		append([]any{}, handleFuncs...)...)}
}

func (_c *MockAppServletRouter_Default_Call) Run(run func(handleFuncs ...servlet.HandleFunc[AppServletContext])) *MockAppServletRouter_Default_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []servlet.HandleFunc[AppServletContext]
		variadicArgs := make([]servlet.HandleFunc[AppServletContext], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(servlet.HandleFunc[AppServletContext])
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAppServletRouter_Default_Call) Return(handleGroup servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Default_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockAppServletRouter_Default_Call) RunAndReturn(run func(handleFuncs ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Default_Call {
	_c.Call.Return(run)
	return _c
}

// Group provides a mock function for the type MockAppServletRouter
func (_mock *MockAppServletRouter) Group() servlet.HandleGroup[AppServletContext] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 servlet.HandleGroup[AppServletContext]
	if returnFunc, ok := ret.Get(0).(func() servlet.HandleGroup[AppServletContext]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[AppServletContext])
		}
	}
	return r0
}

// MockAppServletRouter_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockAppServletRouter_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
func (_e *MockAppServletRouter_Expecter) Group() *MockAppServletRouter_Group_Call {
	return &MockAppServletRouter_Group_Call{Call: _e.mock.On("Group")}
}

func (_c *MockAppServletRouter_Group_Call) Run(run func()) *MockAppServletRouter_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppServletRouter_Group_Call) Return(handleGroup servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Group_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockAppServletRouter_Group_Call) RunAndReturn(run func() servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Group_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type MockAppServletRouter
func (_mock *MockAppServletRouter) Handle(v servlet.RequestName, handleFuncs ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext] {
	// servlet.HandleFunc[AppServletContext]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, v)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 servlet.HandleGroup[AppServletContext]
	if returnFunc, ok := ret.Get(0).(func(servlet.RequestName, ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext]); ok {
		r0 = returnFunc(v, handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[AppServletContext])
		}
	}
	return r0
}

// MockAppServletRouter_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockAppServletRouter_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - v servlet.RequestName
//   - handleFuncs ...servlet.HandleFunc[AppServletContext]
func (_e *MockAppServletRouter_Expecter) Handle(v any, handleFuncs ...any) *MockAppServletRouter_Handle_Call {
	return &MockAppServletRouter_Handle_Call{Call: _e.mock.On("Handle",
		append([]any{v}, handleFuncs...)...)}
}

func (_c *MockAppServletRouter_Handle_Call) Run(run func(v servlet.RequestName, handleFuncs ...servlet.HandleFunc[AppServletContext])) *MockAppServletRouter_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 servlet.RequestName
		if args[0] != nil {
			arg0 = args[0].(servlet.RequestName)
		}
		var arg1 []servlet.HandleFunc[AppServletContext]
		variadicArgs := make([]servlet.HandleFunc[AppServletContext], len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(servlet.HandleFunc[AppServletContext])
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAppServletRouter_Handle_Call) Return(handleGroup servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Handle_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockAppServletRouter_Handle_Call) RunAndReturn(run func(v servlet.RequestName, handleFuncs ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Route provides a mock function for the type MockAppServletRouter
func (_mock *MockAppServletRouter) Route(v servlet.RequestName) servlet.HandleGroup[AppServletContext] {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 servlet.HandleGroup[AppServletContext]
	if returnFunc, ok := ret.Get(0).(func(servlet.RequestName) servlet.HandleGroup[AppServletContext]); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[AppServletContext])
		}
	}
	return r0
}

// MockAppServletRouter_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockAppServletRouter_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - v servlet.RequestName
func (_e *MockAppServletRouter_Expecter) Route(v any) *MockAppServletRouter_Route_Call {
	return &MockAppServletRouter_Route_Call{Call: _e.mock.On("Route", v)}
}

func (_c *MockAppServletRouter_Route_Call) Run(run func(v servlet.RequestName)) *MockAppServletRouter_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 servlet.RequestName
		if args[0] != nil {
			arg0 = args[0].(servlet.RequestName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppServletRouter_Route_Call) Return(handleGroup servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Route_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockAppServletRouter_Route_Call) RunAndReturn(run func(v servlet.RequestName) servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Route_Call {
	_c.Call.Return(run)
	return _c
}

// Use provides a mock function for the type MockAppServletRouter
func (_mock *MockAppServletRouter) Use(handleFuncs ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext] {
	// servlet.HandleFunc[AppServletContext]
	_va := make([]any, len(handleFuncs))
	for _i := range handleFuncs {
		_va[_i] = handleFuncs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Use")
	}

	var r0 servlet.HandleGroup[AppServletContext]
	if returnFunc, ok := ret.Get(0).(func(...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext]); ok {
		r0 = returnFunc(handleFuncs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servlet.HandleGroup[AppServletContext])
		}
	}
	return r0
}

// MockAppServletRouter_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockAppServletRouter_Use_Call struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - handleFuncs ...servlet.HandleFunc[AppServletContext]
func (_e *MockAppServletRouter_Expecter) Use(handleFuncs ...any) *MockAppServletRouter_Use_Call {
	return &MockAppServletRouter_Use_Call{Call: _e.mock.On("Use",
		append([]any{}, handleFuncs...)...)}
}

func (_c *MockAppServletRouter_Use_Call) Run(run func(handleFuncs ...servlet.HandleFunc[AppServletContext])) *MockAppServletRouter_Use_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []servlet.HandleFunc[AppServletContext]
		variadicArgs := make([]servlet.HandleFunc[AppServletContext], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(servlet.HandleFunc[AppServletContext])
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAppServletRouter_Use_Call) Return(handleGroup servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Use_Call {
	_c.Call.Return(handleGroup)
	return _c
}

func (_c *MockAppServletRouter_Use_Call) RunAndReturn(run func(handleFuncs ...servlet.HandleFunc[AppServletContext]) servlet.HandleGroup[AppServletContext]) *MockAppServletRouter_Use_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApplet creates a new instance of MockApplet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplet {
	mock := &MockApplet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplet is an autogenerated mock type for the Applet type
type MockApplet struct {
	mock.Mock
}

type MockApplet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplet) EXPECT() *MockApplet_Expecter {
	return &MockApplet_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockApplet
func (_mock *MockApplet) Exec(name CommandName, reader io.Reader) (io.ReadCloser, error) {
	ret := _mock.Called(name, reader)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(CommandName, io.Reader) (io.ReadCloser, error)); ok {
		return returnFunc(name, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(CommandName, io.Reader) io.ReadCloser); ok {
		r0 = returnFunc(name, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(CommandName, io.Reader) error); ok {
		r1 = returnFunc(name, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplet_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockApplet_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - name CommandName
//   - reader io.Reader
func (_e *MockApplet_Expecter) Exec(name any, reader any) *MockApplet_Exec_Call {
	return &MockApplet_Exec_Call{Call: _e.mock.On("Exec", name, reader)}
}

func (_c *MockApplet_Exec_Call) Run(run func(name CommandName, reader io.Reader)) *MockApplet_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CommandName
		if args[0] != nil {
			arg0 = args[0].(CommandName)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplet_Exec_Call) Return(readCloser io.ReadCloser, err error) *MockApplet_Exec_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockApplet_Exec_Call) RunAndReturn(run func(name CommandName, reader io.Reader) (io.ReadCloser, error)) *MockApplet_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAppletModule creates a new instance of MockAppletModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppletModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppletModule {
	mock := &MockAppletModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppletModule is an autogenerated mock type for the AppletModule type
type MockAppletModule struct {
	mock.Mock
}

type MockAppletModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppletModule) EXPECT() *MockAppletModule_Expecter {
	return &MockAppletModule_Expecter{mock: &_m.Mock}
}

// SetupToApplet provides a mock function for the type MockAppletModule
func (_mock *MockAppletModule) SetupToApplet(router AppServletRouter) error {
	ret := _mock.Called(router)

	if len(ret) == 0 {
		panic("no return value specified for SetupToApplet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(AppServletRouter) error); ok {
		r0 = returnFunc(router)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppletModule_SetupToApplet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupToApplet'
type MockAppletModule_SetupToApplet_Call struct {
	*mock.Call
}

// SetupToApplet is a helper method to define mock.On call
//   - router AppServletRouter
func (_e *MockAppletModule_Expecter) SetupToApplet(router any) *MockAppletModule_SetupToApplet_Call {
	return &MockAppletModule_SetupToApplet_Call{Call: _e.mock.On("SetupToApplet", router)}
}

func (_c *MockAppletModule_SetupToApplet_Call) Run(run func(router AppServletRouter)) *MockAppletModule_SetupToApplet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 AppServletRouter
		if args[0] != nil {
			arg0 = args[0].(AppServletRouter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppletModule_SetupToApplet_Call) Return(err error) *MockAppletModule_SetupToApplet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppletModule_SetupToApplet_Call) RunAndReturn(run func(router AppServletRouter) error) *MockAppletModule_SetupToApplet_Call {
	_c.Call.Return(run)
	return _c
}
