package nodesearchfile

import (
	"errors"
	"pan/lib/feature"
	"pan/lib/repository"
	"pan/lib/web"
	"strconv"
	"strings"

	"gorm.io/gorm"
)

var ErrNodeSearchFileDBUnavailable = errors.New("searchfile.NodeSearchFileRepository Error: Database unavailable")
var ErrNodeSearchFileNotFound = errors.New("searchfile.NodeSearchFileRepository Error: Not Found")
var ErrNodeSearchFileRepoUnavailable = errors.New("searchfile.NodeSearchFileRepository Error: Unavailable")

// TableName returns the default table name for the NodeSearchFile model.
// The table name is used by Gorm when querying the database.
func (NodeSearchFile) TableName() string {
	return "node_file_rates"
}

func generateTableNameWithNodeSearchFile(searchFile *NodeSearchFile, taskId uint64) string {
	return strings.Join([]string{searchFile.TableName(), strconv.FormatUint(taskId, 10)}, "_")
}

// NodeSearchFileWithTaskID returns a function that can be used as a Gorm scope.
// The returned function takes a Gorm DB instance and returns a new Gorm DB instance
// that is scoped to the table name generated by calling generateTableNameWithNodeSearchFile
// with the given searchFile and taskId.
//
// The function is used to scope the Gorm DB instance to the table name
// specific to the given task ID when querying the database.
func NodeSearchFileWithTaskID(searchFile *NodeSearchFile, taskId uint64) func(db *gorm.DB) *gorm.DB {
	return func(db *gorm.DB) *gorm.DB {
		tableName := generateTableNameWithNodeSearchFile(searchFile, taskId)
		return db.Table(tableName)
	}
}

type NodeSearchFileRepository interface {
	repository.Repository
	// Init initializes the database table for the given task ID.
	// The function checks if the table already exists, and if not, creates it.
	// If the table already exists, the function does nothing.
	// If the database is unavailable, the function returns ErrNodeSearchFileDBUnavailable.
	// If the function fails to create the table, the function returns the error.
	Init(taskId uint64) error
	// Destroy removes the database table for the given task ID.
	// If the database is unavailable, the function returns ErrNodeSearchFileDBUnavailable.
	// If the function fails to drop the table, the function returns the error.
	Destroy(taskId uint64) error
	// Search retrieves NodeSearchFiles associated with the specified task ID, applying
	// the given range condition for pagination. It returns the total number of results,
	// a slice of NodeSearchFiles, and an error if any issues occur during the query.
	// If the database is unavailable, it returns ErrNodeSearchFileDBUnavailable.
	Search(taskId uint64, condition web.RangeCondition) (int64, []NodeSearchFile, error)
	// Save saves the given NodeSearchFile to the database table associated with the
	// specified task ID. It returns the saved NodeSearchFile and an error if any issues
	// occur during the query. If the database is unavailable, it returns
	// ErrNodeSearchFileDBUnavailable.
	Save(taskId uint64, searchFile NodeSearchFile) (NodeSearchFile, error)
}

type stdSearchFileRepository struct {
	feature.Repository
}

// NewNodeSearchFileRepository creates a new instance of NodeSearchFileRepository using the
// provided Gorm DB instance. If the database connection is nil, subsequent repository
// operations will return ErrNodeSearchFileDBUnavailable.
func NewNodeSearchFileRepository() NodeSearchFileRepository {
	return &stdSearchFileRepository{}
}

var _ = (NodeSearchFileRepository)((*stdSearchFileRepository)(nil))

// Init initializes the database table for the given task ID.
// The function checks if the table already exists, and if not, creates it.
// If the table already exists, the function does nothing.
// If the database is unavailable, the function returns ErrNodeSearchFileDBUnavailable.
// If the function fails to create the table, the function returns the error.
func (repo *stdSearchFileRepository) Init(taskId uint64) error {
	db := repo.DB()
	if db == nil {
		return ErrNodeSearchFileDBUnavailable
	}
	var model NodeSearchFile
	db = db.Scopes(NodeSearchFileWithTaskID(&model, taskId))
	migrator := db.Migrator()
	if migrator.HasTable(&model) {
		return db.Delete(&model).Error
	}
	return migrator.CreateTable(&model)
}

// Destroy removes the database table associated with the given task ID.
// If the database connection is unavailable, it returns ErrNodeSearchFileDBUnavailable.
// If the table exists, it drops the table and returns any error encountered during this process.
// If the table does not exist, it returns nil.

func (repo *stdSearchFileRepository) Destroy(taskId uint64) error {
	db := repo.DB()
	if db == nil {
		return ErrNodeSearchFileDBUnavailable
	}
	var model NodeSearchFile
	db = db.Scopes(NodeSearchFileWithTaskID(&model, taskId))
	migrator := db.Migrator()
	if migrator.HasTable(&model) {
		return migrator.DropTable(&model)
	}
	return nil
}

// Search retrieves NodeSearchFiles associated with the specified task ID, applying
// the given range condition for pagination. It returns the total number of results,
// a slice of NodeSearchFiles, and an error if any issues occur during the query.
// If the database is unavailable, it returns ErrNodeSearchFileDBUnavailable.
// If the table for the task ID does not exist, the function returns nil for the total
// and the slice of NodeSearchFiles, and no error.
func (repo *stdSearchFileRepository) Search(taskId uint64, condition web.RangeCondition) (int64, []NodeSearchFile, error) {
	db := repo.DB()
	if db == nil {
		return 0, nil, ErrNodeSearchFileDBUnavailable
	}
	var model NodeSearchFile
	db = db.Scopes(NodeSearchFileWithTaskID(&model, taskId))

	migrator := db.Migrator()
	if !migrator.HasTable(&model) {
		return 0, nil, nil
	}

	total := int64(0)
	results := db.Model(&NodeSearchFile{}).Count(&total)

	if results.Error != nil || total <= 0 {
		return total, nil, results.Error
	}

	db = db.Scopes(web.PaginateWithRangeCondition(&condition))
	var searchFiles []NodeSearchFile

	results = db.Find(&searchFiles)
	return total, searchFiles, results.Error
}

// Save saves the given NodeSearchFile to the database table associated with the
// specified task ID. It returns the saved NodeSearchFile and an error if any issues
// occur during the query. If the database connection is unavailable, it returns
// ErrNodeSearchFileDBUnavailable.
//
// If the table for the task ID does not exist, it returns ErrNodeSearchFileRepoUnavailable.
//
// If the NodeSearchFile was not found, it returns ErrNodeSearchFileNotFound.
func (repo *stdSearchFileRepository) Save(taskId uint64, searchFile NodeSearchFile) (NodeSearchFile, error) {
	db := repo.DB()
	if db == nil {
		return NodeSearchFile{}, ErrNodeSearchFileDBUnavailable
	}

	db = db.Scopes(NodeSearchFileWithTaskID(&searchFile, taskId))
	migrator := db.Migrator()
	if !migrator.HasTable(&NodeSearchFile{}) {
		return NodeSearchFile{}, ErrNodeSearchFileRepoUnavailable
	}

	results := db.Save(&searchFile)
	if results.Error == nil && results.RowsAffected != 1 {
		return searchFile, ErrNodeSearchFileNotFound
	}
	return searchFile, results.Error
}
